Repository IDAES/idaes-pse, pull requests merged in 2020-12, with the labels that each got.

#79 Remove CircleCI configuration
  .circleci/config.yml
Labels: Priority:High

#57 Fix PySMO's Jupyter print problems
  idaes/surrogate/pysmo/kriging.py
  idaes/surrogate/pysmo/polynomial_regression.py
  idaes/surrogate/pysmo/radial_basis_function.py
Labels: Priority:High

#97 Adding tray unit model to support HDA case study
  idaes/generic_models/unit_models/distillation/__init__.py
  idaes/generic_models/unit_models/distillation/condenser.py
  idaes/generic_models/unit_models/distillation/reboiler.py
  idaes/generic_models/unit_models/distillation/tests/test_conventional_tray.py
  idaes/generic_models/unit_models/distillation/tests/test_feed_tray.py
  idaes/generic_models/unit_models/distillation/tests/test_partial_condenser.py
  idaes/generic_models/unit_models/distillation/tests/test_reboiler.py
  idaes/generic_models/unit_models/distillation/tests/test_total_condenser.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_column.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_side_liq_draw.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_side_vap_draw.py
  idaes/generic_models/unit_models/distillation/tray.py
  idaes/generic_models/unit_models/distillation/tray_column.py
Labels: Priority:High, unit models

#112 PowerPlantLibrary: Boiler heat exchanger2D and water tank models
  docs/technical_specs/model_libraries/power_generation/unit_models/boiler2D_1.png
  docs/technical_specs/model_libraries/power_generation/unit_models/boiler2D_2.png
  docs/technical_specs/model_libraries/power_generation/unit_models/boiler_heat_exchanger2D.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/index.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/watertank.rst
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/power_generation/unit_models/tests/test_heat_exchanger2D.py
  idaes/power_generation/unit_models/tests/test_watertank.py
  idaes/power_generation/unit_models/watertank.py
Labels: Priority:High

#113 Fixing pressure_changer test to work with upcoming Pyomo update
  idaes/generic_models/unit_models/tests/test_pressure_changer.py
Labels: Priority:High

#118 Adding checks on state_bounds argument to find unexpected keys
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
Labels: Priority:High, bug, property packages

#114 Power plant library: drum1D and waterpipe models, tests, and documentation
  docs/technical_specs/model_libraries/power_generation/unit_models/drum1D.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/drum1D_1.png
  docs/technical_specs/model_libraries/power_generation/unit_models/drum1D_2.png
  docs/technical_specs/model_libraries/power_generation/unit_models/index.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/waterpipe.rst
  idaes/power_generation/unit_models/drum1D.py
  idaes/power_generation/unit_models/tests/test_drum1D.py
  idaes/power_generation/unit_models/tests/test_waterpipe.py
  idaes/power_generation/unit_models/waterpipe.py
Labels: Priority:High

#123 Fixing circular import issue in set_param_value method
  idaes/core/components.py
  idaes/core/util/misc.py
  idaes/core/util/tests/test_misc.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/utility.py
  idaes/generic_models/properties/core/pure/NIST.py
  idaes/generic_models/properties/core/pure/Perrys.py
  idaes/generic_models/properties/core/pure/RPP.py
  idaes/generic_models/properties/core/pure/RPP3.py
  idaes/generic_models/properties/core/pure/tests/test_RPP3.py
  idaes/generic_models/properties/core/reactions/dh_rxn.py
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/rate_constant.py
Labels: Priority:High, bug, property packages, testing

#126 Adding support for cp calculations to generic property framework
  idaes/core/components.py
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:High, enhancement, property packages

#107 Add Save functionality to flowsheet visualizer (IFV)
  idaes/config.py
  idaes/core/flowsheet_model.py
  idaes/ui/flowsheet.py
  idaes/ui/flowsheet_comparer.py
  idaes/ui/flowsheet_serializer.py
  idaes/ui/fsvis/app.py
  idaes/ui/fsvis/fsvis.py
  idaes/ui/fsvis/model_server.py
  idaes/ui/fsvis/persist.py
  idaes/ui/fsvis/server.py
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/fsvis/static/js/paper.js
  idaes/ui/fsvis/static/js/toolbar.js
  idaes/ui/fsvis/templates/index.html
  idaes/ui/fsvis/tests/sample_visualization.py
  idaes/ui/fsvis/tests/test_flask_server.py
  idaes/ui/fsvis/tests/test_fsvis.py
  idaes/ui/fsvis/tests/test_persist.py
  idaes/ui/icon_mapping.py
  idaes/ui/icons.py
  idaes/ui/link_position_mapping.py
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/test_flowsheet.py
  idaes/ui/tests/test_flowsheet_comparer.py
  idaes/ui/tests/test_flowsheet_serializer.py
  idaes/ui/tests/test_icons.py
  idaes/ui/tests/test_link_position_mapping.py
  setup.py
Labels: Priority:Mid

#125 Power Plant Library: 3 streams heat exchanger unit model, tests, and documentation
  docs/technical_specs/model_libraries/power_generation/unit_models/boiler_heat_exchanger_3streams.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/index.rst
  idaes/power_generation/unit_models/heat_exchanger_3streams.py
  idaes/power_generation/unit_models/tests/test_heat_exchanger_3streams.py
Labels: Priority:High

#124 Power plant costing library: methods, documentation, and testing
  docs/technical_specs/model_libraries/power_generation/costing/power_plant_costing.rst
  docs/technical_specs/model_libraries/power_generation/index.rst
  idaes/power_generation/costing/BB_costing_exponents.json
  idaes/power_generation/costing/BB_costing_parameters.json
  idaes/power_generation/costing/costing_dictionaries.py
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/costing/sCO2_costing_parameters.json
  idaes/power_generation/costing/tests/test_power_plant_costing.py
Labels: Priority:High

#109 Update default binary download version to 2.2.2
  idaes/config.py
Labels: Priority:High

#53 Heatexchanger Cleanup and Dynamic NTU Condenser Init
  idaes/generic_models/unit_models/heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_heater.py
  idaes/generic_models/unit_models/tests/test_pressure_changer.py
  idaes/power_generation/unit_models/helm/condenser_ntu.py
  idaes/power_generation/unit_models/helm/tests/test_condenser_ntu.py
Labels: Priority:High, bug

#115 Removing old turbine and valve models that use any prop pack
  docs/technical_specs/model_libraries/power_generation/unit_models/steam_valve.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_inlet.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_multistage.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_outlet.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_stage.rst
  idaes/power_generation/unit_models/__init__.py
  idaes/power_generation/unit_models/helm/convergence/heater.py
  idaes/power_generation/unit_models/helm/turbine_outlet.py
  idaes/power_generation/unit_models/tests/test_turb_outlet.py
  idaes/power_generation/unit_models/tests/test_turbine_inlet.py
  idaes/power_generation/unit_models/tests/test_turbine_multistage.py
  idaes/power_generation/unit_models/tests/test_turbine_stage.py
  idaes/power_generation/unit_models/turbine_inlet.py
  idaes/power_generation/unit_models/turbine_multistage.py
  idaes/power_generation/unit_models/turbine_outlet.py
  idaes/power_generation/unit_models/turbine_stage.py
Labels: Priority:High

#134 Generic costing: improvements to break the cost into multiple units, initialize costing, and scale model
  docs/technical_specs/core/util/unit_costing.rst
  idaes/core/flowsheet_model.py
  idaes/core/unit_model.py
  idaes/core/util/tests/test_unit_costing.py
  idaes/core/util/unit_costing.py
  idaes/generic_models/unit_models/cstr.py
  idaes/generic_models/unit_models/flash.py
  idaes/generic_models/unit_models/heat_exchanger.py
  idaes/generic_models/unit_models/plug_flow_reactor.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/generic_models/unit_models/stoichiometric_reactor.py
  idaes/generic_models/unit_models/tests/test_flash.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_pressure_changer.py
Labels: Priority:High

#139 Correcting units of measurement in docs
  docs/user_guide/components/property_package/general/pure/NIST.rst
  docs/user_guide/components/property_package/general/pure/Perrys.rst
  docs/user_guide/components/property_package/general/pure/RPP.rst
  docs/user_guide/components/property_package/general/pure/RPP3.rst
Labels: Priority:Mid, documentation, property packages
