Repository IDAES/idaes-pse, pull requests merged in 2021-01, with the labels that each got.

#137 Speed up Helmholtz EoS with units of measure.
  idaes/generic_models/properties/helmholtz/helmholtz.py
  idaes/generic_models/properties/iapws95.py
  idaes/generic_models/properties/swco2.py
  idaes/generic_models/properties/tests/test_iapws95_basic.py
  idaes/generic_models/properties/tests/test_swco2_basic.py
  idaes/ui/tests/demo_flowsheet.json
Labels: Priority:High

#110 Improvements to GitHub Actions CI: integration tests on PR approval, code coverage
  .github/actions/build-docs/action.yml
  .github/actions/pylint/action.yml
  .github/actions/pytest/action.yml
  .github/actions/setup-idaes/action.yml
  .github/workflows/integration-tests.yml
  .github/workflows/main.yml
  .github/workflows/pr-approved.yml
  .github/workflows/pr.yml
  .github/workflows/pull-request-main.yml
  README.md
Labels: Priority:High, approved, testing

#141 Adding option to control behaviour of heat of formation
  docs/user_guide/components/property_package/general/global_options.rst
  docs/user_guide/components/property_package/general/index.rst
  docs/user_guide/components/property_package/general/pure/NIST.rst
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/pure/NIST.py
  idaes/generic_models/properties/core/pure/Perrys.py
  idaes/generic_models/properties/core/pure/RPP.py
  idaes/generic_models/properties/core/pure/RPP3.py
  idaes/generic_models/properties/core/pure/tests/test_NIST.py
  idaes/generic_models/properties/core/pure/tests/test_Perrys.py
  idaes/generic_models/properties/core/pure/tests/test_RPP.py
  idaes/generic_models/properties/core/pure/tests/test_RPP3.py
Labels: Priority:Mid, approved, bug, property packages

#147 Fix tutorial link and improve descriptions
  docs/tutorials_examples.rst
Labels: Priority:Mid, approved, documentation

#143 Updates to distillation initialization method
  idaes/generic_models/unit_models/distillation/condenser.py
  idaes/generic_models/unit_models/distillation/reboiler.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_column.py
  idaes/generic_models/unit_models/distillation/tray.py
  idaes/generic_models/unit_models/distillation/tray_column.py
Labels: Priority:High, approved, enhancement, unit models

#142 Adding support for true and apparent species lists
  idaes/core/components.py
  idaes/core/property_base.py
  idaes/core/tests/test_components.py
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/properties/core/generic/tests/test_electrolyte_components.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/phase_equil/bubble_dew.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
Labels: Priority:High, approved, enhancement, property packages

#159 Basic Adiabatic Valve Model
  docs/technical_specs/model_libraries/generic/unit_models/index.rst
  docs/technical_specs/model_libraries/generic/unit_models/valve.rst
  idaes/core/util/testing.py
  idaes/generic_models/control/tests/test_steam_tank.py
  idaes/generic_models/unit_models/__init__.py
  idaes/generic_models/unit_models/tests/test_valve.py
  idaes/generic_models/unit_models/valve.py
  idaes/power_generation/unit_models/__init__.py
  idaes/power_generation/unit_models/tests/test_valve_steam.py
  idaes/power_generation/unit_models/valve_steam.py
Labels: Priority:High, approved, unit models

#95 Add high-level IDAES IP description
  docs/_images/IDAES-IP.png
  docs/index.rst
  docs/user_guide/concepts.rst
Labels: Priority:Mid, approved, documentation

#168 Fixes to GitHub Actions CI workflows to address coverage report issues
  .github/workflows/core.yml
  .github/workflows/integration.yml
  .github/workflows/pr.yml
  README.md
Labels: CI:run-integration, Priority:High

#171 Modify name of pytest job in integration workflow
  .github/workflows/core.yml
  .github/workflows/integration.yml
Labels: Priority:High, enhancement, testing

#179 GitHub Actions CI hotfix: use correct field for integration workflow trigger on PRs
  .github/workflows/integration.yml
Labels: CI:run-integration, Priority:High, bug, testing

#163 Updatedate get-extensions command, prep for OSX
  idaes/__init__.py
  idaes/commands/extensions.py
  idaes/commands/tests/test_commands.py
  idaes/config.py
  idaes/solvers.py
  idaes/tests/test_download_bin.py
Labels: CI:run-integration, Priority:High

#161 Add config options for default state var bounds
  docs/technical_specs/model_libraries/generic/property_models/helmholtz.rst
  docs/technical_specs/model_libraries/generic/property_models/iapws95.rst
  docs/technical_specs/model_libraries/generic/property_models/index.rst
  docs/technical_specs/model_libraries/generic/property_models/swco2.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/feedwater_heater_0D.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/feedwater_heater_condensing_0D.rst
  idaes/generic_models/properties/helmholtz/helmholtz.py
  idaes/generic_models/properties/iapws95.py
  idaes/generic_models/properties/swco2.py
  idaes/generic_models/properties/tests/test_iapws95.py
Labels: CI:run-integration, Priority:High

#167 Updated bfb model to address singularity in time-DAE and algebraic Jacobians.
  docs/technical_specs/model_libraries/gas_solid_contactors/unit_models/bubbling_fluidized_bed.rst
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
Labels: CI:run-integration, Priority:Mid, unit models

#178 Dynamic power plant models, examples, tests, and documentation
  docs/technical_specs/model_libraries/power_generation/control/pid.rst
  docs/technical_specs/model_libraries/power_generation/flowsheets/SCPC_power_plant.rst
  docs/technical_specs/model_libraries/power_generation/flowsheets/coal_flowrate.png
  docs/technical_specs/model_libraries/power_generation/flowsheets/coordinated_control.png
  docs/technical_specs/model_libraries/power_generation/flowsheets/drum_controller.png
  docs/technical_specs/model_libraries/power_generation/flowsheets/index.rst
  docs/technical_specs/model_libraries/power_generation/flowsheets/power_demand.png
  docs/technical_specs/model_libraries/power_generation/flowsheets/subcr_pc_PFD.png
  docs/technical_specs/model_libraries/power_generation/flowsheets/subcritical_power_plant.rst
  docs/technical_specs/model_libraries/power_generation/index.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/feedwater_heater_0D_dynamic.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/index.rst
  idaes/power_generation/control/pid_controller.py
  idaes/power_generation/control/tests/test_pid_pump.py
  idaes/power_generation/flowsheets/subcritical_power_plant/generic_surrogate_dict.py
  idaes/power_generation/flowsheets/subcritical_power_plant/plant_pfd.svg
  idaes/power_generation/flowsheets/subcritical_power_plant/plant_pfd_result.svg
  idaes/power_generation/flowsheets/subcritical_power_plant/steam_cycle_flowsheet.py
  idaes/power_generation/flowsheets/subcritical_power_plant/subcritical_boiler_flowsheet.py
  idaes/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
  idaes/power_generation/flowsheets/subcritical_power_plant/tests/test_subcritical_flowsheets.py
  idaes/power_generation/properties/flue_gas_ideal.py
  idaes/power_generation/unit_models/__init__.py
  idaes/power_generation/unit_models/boiler_fireside.py
  idaes/power_generation/unit_models/downcomer.py
  idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py
  idaes/power_generation/unit_models/helm/turbine_outlet.py
  idaes/power_generation/unit_models/tests/test_feedwater_heater_dynamic.py
  idaes/power_generation/unit_models/waterwall_section.py
Labels: CI:run-integration, Priority:High

#185 Fix shell escaping issues in GitHub Actions workflows
  .github/actions/display-debug-info/action.yml
  .github/workflows/core.yml
  .github/workflows/integration.yml
Labels: CI:run-integration, testing

#183 Fixing potential recursive loop in StateBlocks
  idaes/core/property_base.py
Labels: CI:run-integration, Priority:Mid, bug, property packages

#188 Avoid false positive in project coverage status checks
  codecov.yml
Labels: CI:run-integration

#187 Improve example for Generic Reaction Framework
  idaes/generic_models/properties/core/examples/reactions/reaction_example.py
Labels: CI:run-integration, Priority:Mid, bug, documentation

#186 Minor Power Model Doc Update
  docs/technical_specs/model_libraries/power_generation/unit_models/feedwater_heater_0D.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/index.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/steam_valve.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_inlet.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_multistage.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_outlet.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_stage.rst
Labels: CI:run-integration

#180 Add ipopt-idaes solver
  idaes/config.py
  idaes/core/plugins/__init__.py
  idaes/core/plugins/solvers.py
  idaes/tests/test_ipopt.py
Labels: CI:run-integration

#138 Adds stream table to UI
  idaes/core/process_base.py
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-grid.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-grid.css.map
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-grid.min.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-grid.min.css.map
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-reboot.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-reboot.css.map
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-reboot.min.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap-reboot.min.css.map
  idaes/ui/fsvis/static/css/bootstrap/bootstrap.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap.css.map
  idaes/ui/fsvis/static/css/bootstrap/bootstrap.min.css
  idaes/ui/fsvis/static/css/bootstrap/bootstrap.min.css.map
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/fsvis/static/js/paper.js
  idaes/ui/fsvis/static/js/stream_table.js
  idaes/ui/fsvis/static/js/toolbar.js
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.js
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.js.map
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.min.js
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.min.js.map
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.js
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.js.map
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.min.js
  idaes/ui/fsvis/static/lib/bootstrap/bootstrap.min.js.map
  idaes/ui/fsvis/templates/index.html
  idaes/ui/fsvis/tests/test_fsvis.py
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
  idaes/ui/tests/test_flowsheet.py
Labels: CI:run-integration, Priority:Mid

#190 Tracking updates to pyomo units handling
  idaes/core/util/tests/test_misc.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/examples/reactions/tests/test_reaction_example.py
  idaes/power_generation/unit_models/drum.py
Labels: CI:run-integration
