Repository IDAES/idaes-pse, pull requests merged in 2021-02, with the labels that each got.

#196 Adding support for molarity to generic properties
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: CI:run-integration, Priority:High, property packages

#192 Update Configuration Docs
  docs/user_guide/configuration.rst
  docs/user_guide/index.rst
  docs_archive/Makefile
  docs_archive/configuration.rst
  idaes/__init__.py
  idaes/config.py
  idaes/tests/test_config.py
  idaes/tests/test_download_bin.py
  idaes/tests/test_ipopt.py
Labels: CI:run-integration, documentation

#197 Fixing misnamed variable in generic reactions
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
Labels: CI:run-integration, Priority:High, bug, property packages

#182 Alamopy surrogate test bug
  idaes/dmf/tests/test_surrmod.py
Labels: CI:run-integration, Priority:High

#191 Fix erroneous value of particle porosity at the solid outlet port
  docs/technical_specs/model_libraries/gas_solid_contactors/unit_models/bubbling_fluidized_bed.rst
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
Labels: CI:run-integration, Priority:High

#199 fixing 2 typos in generic_property.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: CI:run-integration, Priority:High, bug, property packages

#201 fixing molecular weight expression to use mw instead of mw_comp
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: CI:run-integration, Priority:High, bug, property packages

#203 Reorganising tests of generic properties
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
Labels: CI:run-integration, Priority:High, property packages, testing

#198 Address issues with using modules in Config Blocks
  idaes/generic_models/properties/core/examples/ASU_PR.py
  idaes/generic_models/properties/core/examples/BT_PR.py
  idaes/generic_models/properties/core/examples/BT_ideal.py
  idaes/generic_models/properties/core/examples/CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_noncondense.py
  idaes/generic_models/properties/core/generic/tests/test_noncondense_PR.py
  idaes/generic_models/properties/core/generic/tests/test_nonvap.py
  idaes/generic_models/properties/core/generic/tests/test_nonvap_PR.py
  idaes/generic_models/properties/core/generic/utility.py
  idaes/generic_models/properties/core/phase_equil/__init__.py
  idaes/generic_models/properties/core/phase_equil/smooth_VLE.py
  idaes/generic_models/properties/core/phase_equil/tests/test_smooth_VLE.py
  idaes/generic_models/properties/core/pure/NIST.py
  idaes/generic_models/properties/core/pure/Perrys.py
  idaes/generic_models/properties/core/pure/RPP3.py
  idaes/generic_models/properties/core/pure/RPP4.py
  idaes/generic_models/properties/core/pure/RPP5.py
  idaes/generic_models/properties/core/pure/__init__.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/__init__.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger_1D.py
Labels: CI:run-integration, Priority:Mid, bug, property packages

#150 Fixed unit label rotating when the unit model rotates
  idaes/ui/fsvis/static/js/paper.js
Labels: CI:run-integration, Priority:Mid

#206 UI visual improvements
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/fsvis/static/js/paper.js
  idaes/ui/fsvis/static/js/stream_table.js
  idaes/ui/fsvis/static/js/toolbar.js
  idaes/ui/fsvis/templates/index.html
Labels: CI:run-integration

#212 Power Plant documentation improvements
  docs/technical_specs/model_libraries/power_generation/costing/power_plant_costing.rst
  docs/technical_specs/model_libraries/power_generation/flowsheets/subcritical_power_plant.rst
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
Labels: CI:run-integration, Priority:High

#128 Addition of data quality control and fault detection app and documentation
  docs/index.rst
  docs/related_packages/index.rst
  docs/related_packages/pecos.rst
Labels: CI:run-integration, Priority:Mid

#200 Enable newer Pyomo version in setup.py
  .github/actions/setup-idaes/action.yml
  .github/workflows/core.yml
  .github/workflows/integration.yml
  docs/technical_specs/model_libraries/generic/property_models/swco2.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_inlet.rst
  docs/technical_specs/model_libraries/power_generation/unit_models/turbine_outlet.rst
  setup.py
Labels: CI:run-integration, Priority:High

#219 Natural gas properties
  idaes/power_generation/properties/natural_gas_PR.py
  idaes/power_generation/properties/tests/test_NG_PR.py
Labels: CI:run-integration, Priority:High

#149 Degeneracy Hunter
  docs/user_guide/modeling_extensions/diagnostics/index.rst
  docs/user_guide/modeling_extensions/index.rst
  idaes/core/util/model_diagnostics.py
  idaes/core/util/model_statistics.py
  idaes/core/util/tests/test_model_diagnostics.py
  setup.py
Labels: CI:run-integration, Priority:High, enhancement

#222 Add utility workflow to remove labels used to trigger CI workflows
  .github/workflows/util-cleanup.yml
Labels: CI:run-integration, Priority:High, enhancement, testing

#221 Enable integration tests to run automatically on approved PRs
  .github/actions/check-pr-approval/action.yml
  .github/workflows/integration.yml
Labels: CI:run-integration, Priority:High, enhancement, testing

#209 Matopt upgrade
  docs/user_guide/modeling_extensions/matopt/index.rst
  idaes/apps/matopt/README.md
  idaes/apps/matopt/materials/__init__.py
  idaes/apps/matopt/materials/canvas.py
  idaes/apps/matopt/materials/geometry.py
  idaes/apps/matopt/materials/lattices/__init__.py
  idaes/apps/matopt/materials/lattices/cubic_lattice.py
  idaes/apps/matopt/materials/lattices/diamond_lattice.py
  idaes/apps/matopt/materials/lattices/fcc_lattice.py
  idaes/apps/matopt/materials/lattices/lattice.py
  idaes/apps/matopt/materials/lattices/perovskite_lattice.py
  idaes/apps/matopt/materials/lattices/unit_cell_lattice.py
  idaes/apps/matopt/materials/lattices/wurtzite_lattice.py
  idaes/apps/matopt/materials/tiling.py
  idaes/apps/matopt/tests/test_matopt_objects_construction.py
  idaes/apps/matopt/tests/test_matopt_objects_functionality.py
  idaes/apps/matopt/util/util.py
Labels: Priority:High

#211 Bump Extensions Version
  idaes/config.py
  idaes/generic_models/properties/cubic_eos/tests/test_cubic_root.py
Labels: Priority:High

#223 Fixing error in NIST property library
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/pure/NIST.py
  idaes/generic_models/properties/core/pure/tests/test_NIST.py
  idaes/power_generation/properties/natural_gas_PR.py
Labels: Priority:High, bug, property packages

#165 Caprese reorganization
  idaes/apps/caprese/__init__.py
  idaes/apps/caprese/base_class.py
  idaes/apps/caprese/categorize.py
  idaes/apps/caprese/common/config.py
  idaes/apps/caprese/controller.py
  idaes/apps/caprese/dynamic_block.py
  idaes/apps/caprese/examples/cstr_model.py
  idaes/apps/caprese/examples/cstr_nmpc.py
  idaes/apps/caprese/nmpc.py
  idaes/apps/caprese/nmpc_var.py
  idaes/apps/caprese/rolling.py
  idaes/apps/caprese/tests/test_categorize.py
  idaes/apps/caprese/tests/test_controller.py
  idaes/apps/caprese/tests/test_dynamic_block.py
  idaes/apps/caprese/tests/test_nmpc_constructor_1.py
  idaes/apps/caprese/tests/test_nmpc_constructor_2.py
  idaes/apps/caprese/tests/test_nmpc_constructor_3.py
  idaes/apps/caprese/tests/test_nmpc_constructor_4.py
  idaes/apps/caprese/tests/test_nmpc_unit.py
  idaes/apps/caprese/tests/test_nmpc_var.py
  idaes/apps/caprese/tests/test_rolling.py
  idaes/apps/caprese/tests/test_simple_model.py
  idaes/apps/caprese/tests/test_util.py
  idaes/apps/caprese/util.py
  idaes/core/util/scaling.py
Labels: Priority:Mid

#225 Improving header heat transfer (boiler hx 2D model)
  idaes/power_generation/flowsheets/subcritical_power_plant/subcritical_boiler_flowsheet.py
  idaes/power_generation/flowsheets/subcritical_power_plant/tests/subcritical_boiler_init.json.gz
  idaes/power_generation/flowsheets/subcritical_power_plant/tests/test_subcritical_flowsheets.py
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/power_generation/unit_models/drum1D.py
  idaes/power_generation/unit_models/tests/test_drum1D.py
  idaes/power_generation/unit_models/tests/test_heat_exchanger2D.py
Labels: Priority:High, unit models

#215 Enable running examples as part of the integration CI workflow
  .github/actions/check-pr-approval/action.yml
  .github/actions/display-debug-info/action.yml
  .github/actions/run-examples/action.yml
  .github/actions/run-examples/build-config-for-idaes-ci.yml
  .github/workflows/integration.yml
Labels: Priority:High

#216 Adding support for inherent reactions
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/property_base.py
  idaes/core/reaction_base.py
  idaes/core/tests/test_control_volume_0d.py
  idaes/core/tests/test_control_volume_1d.py
  idaes/core/tests/test_property_base.py
  idaes/core/util/testing.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property_integration.py
  idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
  idaes/generic_models/properties/core/reactions/equilibrium_forms.py
  idaes/generic_models/properties/core/reactions/rate_forms.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_forms.py
  idaes/generic_models/properties/core/reactions/tests/test_rate_forms.py
Labels: Priority:High, core, enhancement
