Repository IDAES/idaes-pse, pull requests merged in 2021-08, with the labels that each got.

#446 Allow changing parameters for TEL curve
  idaes/power_generation/unit_models/helm/turbine_outlet.py
Labels: Priority:Normal

#448 Relaxing requirement for generic reactions to have rate form
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
Labels: bug, Priority:Normal, property packages

#456 O&M Costing Update
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/costing/tests/test_NGCC_costing.py
  idaes/power_generation/costing/tests/test_power_plant_costing.py
  idaes/power_generation/flowsheets/ngcc/ngcc.py
  idaes/power_generation/flowsheets/ngcc/ngcc_costing.py
Labels: Priority:Normal

#461 Bump Pyomo tag for pre-release testing
  idaes/apps/caprese/tests/test_controller.py
  idaes/core/process_base.py
  idaes/core/property_base.py
  idaes/core/util/misc.py
  setup.py
Labels: Priority:High, testing, dependencies

#462 Adding energy scaling to mixer unit model
  idaes/generic_models/unit_models/mixer.py
  idaes/generic_models/unit_models/tests/test_mixer.py
Labels: bug, Priority:High, unit models

#464 Fix report() in valve.py
  idaes/generic_models/unit_models/valve.py
Labels: bug, Priority:Normal, unit models

#457 Fixing issue with IndexedArcs in propagate_state
  idaes/core/util/initialization.py
  idaes/core/util/misc.py
  idaes/core/util/tests/test_initialization.py
  idaes/core/util/tests/test_misc.py
Labels: bug, Priority:Normal, core

#466 Minor fix in Generic Property Model
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: bug, Priority:Normal, property packages

#463 Update Pyomo version
  setup.py
Labels: Priority:High

#286 Categorize variables and constraints in Caprese
  idaes/apps/caprese/categorize.py
  idaes/apps/caprese/common/config.py
  idaes/apps/caprese/controller.py
  idaes/apps/caprese/dynamic_block.py
  idaes/apps/caprese/examples/cstr_reduced.py
  idaes/apps/caprese/tests/test_categorize.py
  idaes/apps/caprese/tests/test_categorize_cstr.py
  idaes/apps/caprese/tests/test_dynamic_block.py
  idaes/apps/caprese/util.py
  setup.py
Labels: Priority:High

#473 Bumping Pyomo tag to 6.1.2
  setup.py
Labels: Priority:High

#468 Remove `OrderedSet.__getitem__` from Caprese modules
  idaes/apps/caprese/dynamic_block.py
  idaes/apps/caprese/util.py
  setup.py
Labels: Priority:High

#470 Fixing some deprecation warnings
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
Labels: bug, Priority:High, core

#437 Degeneracy Hunter: minor bug fix
  idaes/core/util/model_diagnostics.py
Labels: Priority:Normal

#447 Add a command to print a bunch of environment info
  docs/user_guide/commands/env_info.rst
  docs/user_guide/commands/get_extensions.rst
  docs/user_guide/commands/index.rst
  idaes/commands/convergence.py
  idaes/commands/env_info.py
  idaes/commands/tests/test_commands.py
  idaes/commands/wrap_solver_wsl.py
  idaes/core/util/env_info.py
  idaes/core/util/model_serializer.py
  idaes/core/util/tests/test_env_info.py
  idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
  idaes/power_generation/unit_models/helm/turbine_multistage.py
  idaes/tests/test_solvers.py
Labels: Priority:Normal

#474 Ensuring constraint scaling maintains constraint type
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
Labels: bug, Priority:High, core
