Repository IDAES/idaes-pse, pull requests merged in 2021-11, with the labels that each got.

#543 Update Perrys method for Equation Form 2
  docs/user_guide/components/property_package/general/pure/Perrys.rst
  idaes/generic_models/properties/core/pure/Perrys.py
  idaes/generic_models/properties/core/pure/tests/test_Perrys.py
Labels: Priority:Normal

#572 Solvent Reboiler Model
  idaes/core/util/testing.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_vle.py
  idaes/generic_models/properties/core/generic/utility.py
  idaes/generic_models/properties/core/phase_equil/bubble_dew.py
  idaes/generic_models/properties/core/phase_equil/henry.py
  idaes/generic_models/properties/core/phase_equil/tests/test_henry.py
  idaes/generic_models/unit_models/column_models/solvent_condenser.py
  idaes/generic_models/unit_models/column_models/solvent_reboiler.py
  idaes/generic_models/unit_models/column_models/tests/test_solvent_condenser.py
  idaes/generic_models/unit_models/column_models/tests/test_solvent_reboiler.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_vapor.py
Labels: Priority:High, property packages, unit models

#585 Modify Docs Styling (CSS & Logos)
  docs/conf.py
  docs/images/footer_logo_CMU.jpg
  docs/images/footer_logo_CMU.png
  docs/static/css/custom.css
Labels: documentation, Priority:Normal

#589 Phe new
  idaes/generic_models/unit_models/plate_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_plate_heat_exchanger.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_vapor.py
Labels: Priority:High, unit models

#591 Feed doc tweak
  docs/technical_specs/model_libraries/generic/unit_models/feed.rst
Labels: documentation, Priority:Normal

#454 TGA model files
  docs/technical_specs/model_libraries/gas_solid_contactors/flowsheets/dyn_TGA_example.rst
  docs/technical_specs/model_libraries/gas_solid_contactors/flowsheets/index.rst
  docs/technical_specs/model_libraries/gas_solid_contactors/unit_models/fixed_bed_0D.rst
  docs/technical_specs/model_libraries/gas_solid_contactors/unit_models/index.rst
  idaes/gas_solid_contactors/flowsheets/dyn_TGA_example.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/solid_phase_thermo.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/solid_phase_thermo.py
  idaes/gas_solid_contactors/unit_models/__init__.py
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/fixed_bed_0D.py
  idaes/gas_solid_contactors/unit_models/moving_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
  idaes/gas_solid_contactors/unit_models/tests/test_FB0D.py
  idaes/gas_solid_contactors/unit_models/tests/test_MB.py
Labels: Priority:Low

#590 Generic heat exchanger using NTU method and MEA case example
  docs/technical_specs/model_libraries/generic/unit_models/heat_exchanger_ntu.rst
  docs/technical_specs/model_libraries/generic/unit_models/index.rst
  docs/technical_specs/model_libraries/power_generation/carbon_capture/mea_solvent_system/unit_models/phe.rst
  idaes/core/property_meta.py
  idaes/generic_models/unit_models/__init__.py
  idaes/generic_models/unit_models/heat_exchanger_ntu.py
  idaes/generic_models/unit_models/plate_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_hx_ntu.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/tests/test_mea_solvent.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/phe.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/plate_heat_exchanger.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_phe.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_plate_heat_exchanger.py
Labels: enhancement, Priority:High, unit models

#599 Fixing some bugs in alamopy wrapper
  idaes/surrogate/alamopy.py
  idaes/surrogate/tests/test_alamopy.py
Labels: bug, Priority:Normal, core

#600 Updating Pyomo version to the 6.2 release
  README.md
  idaes/core/util/tables.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/ui/tests/test_flowsheet.py
  setup.py
Labels: Priority:High

#607 Configure Codecov to improve when report updates are created
  codecov.yml
Labels: Priority:Normal

#606 Fixing indexing issue in separator initialization
  idaes/generic_models/unit_models/separator.py
Labels: bug, Priority:Normal, unit models

#603 Adding option to use external length variable in 1D control volumes
  docs/technical_specs/core/control_volume_1d.rst
  idaes/core/control_volume1d.py
  idaes/core/tests/test_control_volume_1d.py
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/moving_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
  idaes/gas_solid_contactors/unit_models/tests/test_MB.py
Labels: enhancement, Priority:High, core

#604 Updates to Surrogate Visualization Module
  idaes/surrogate/plotting/sm_plotter.py
Labels: enhancement, Priority:High, core

#595 Update Sphinx theme to address unordered list spacing issues
  docs/conf.py
  docs/static/css/theme.css
  requirements-dev.txt
Labels: Priority:Normal
