Repository IDAES/idaes-pse, pull requests merged in 2021-09, with the labels that each got.

#472 Fix mixer and spe scale when components not in a phase
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/unit_models/mixer.py
  idaes/generic_models/unit_models/tests/test_mixer.py
Labels: bug, Priority:High

#481 Correcting units for activity-based rate and equilibrium constants
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/rate_constant.py
Labels: bug, Priority:High, property packages

#483 Use consistent randomness sources in PySMO sampling methods
  idaes/surrogate/pysmo/sampling.py
Labels: enhancement, Priority:Normal

#492 Update some out of date copyright headers
  idaes/commands/wrap_solver_wsl.py
  idaes/core/util/tests/test_utility_minimization.py
  idaes/core/util/utility_minimization.py
  idaes/generic_models/properties/core/phase_equil/tests/test_henry.py
  idaes/generic_models/properties/core/reactions/tests/test_solubility_product_verification.py
  idaes/generic_models/unit_models/skeleton_model.py
  idaes/generic_models/unit_models/tests/test_skeleton_unit_model.py
  idaes/power_generation/costing/tests/test_NGCC_costing.py
Labels: Priority:Normal

#496 Fix Documentation Typos
  docs/technical_specs/model_libraries/generic/unit_models/flash.rst
  docs/user_guide/modeling_extensions/surrogate/alamopy/index.rst
  docs/user_guide/modeling_extensions/surrogate/helmet/index.rst
  docs/user_guide/modeling_extensions/surrogate/pysmo/pysmo_sampling_properties.rst
  docs/user_guide/modeling_extensions/surrogate/ripe/index.rst
  idaes/core/process_base.py
  idaes/core/process_block.py
Labels: documentation, Priority:Normal

#487 Fix problem with mixing ideal and cubic eos
  idaes/generic_models/properties/core/eos/ceos.py
Labels: bug, Priority:Normal

#489 Reimplement _get_state_from_port
  idaes/core/unit_model.py
  idaes/core/util/tables.py
  idaes/core/util/tests/test_tables.py
Labels: Priority:Normal, core

#498 Update Tagged SVG Output to use ModelTagGroups
  docs/technical_specs/core/util/tags.rst
  idaes/core/util/misc.py
  idaes/core/util/tags.py
  idaes/core/util/tests/test_tag_svg.py
  idaes/core/util/tests/test_tags.py
Labels: Priority:Normal

#486 Deprecating old list_of config validators
  idaes/core/components.py
  idaes/core/control_volume_base.py
  idaes/core/flowsheet_model.py
  idaes/core/property_base.py
  idaes/core/reaction_base.py
  idaes/core/unit_model.py
  idaes/core/util/config.py
  idaes/core/util/tests/test_config.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/hetero_reactions.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/hetero_reactions.py
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/moving_bed.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/unit_models/cstr.py
  idaes/generic_models/unit_models/distillation/reboiler.py
  idaes/generic_models/unit_models/distillation/tray.py
  idaes/generic_models/unit_models/distillation/tray_column.py
  idaes/generic_models/unit_models/equilibrium_reactor.py
  idaes/generic_models/unit_models/flash.py
  idaes/generic_models/unit_models/gibbs_reactor.py
  idaes/generic_models/unit_models/heat_exchanger_1D.py
  idaes/generic_models/unit_models/heater.py
  idaes/generic_models/unit_models/mixer.py
  idaes/generic_models/unit_models/plug_flow_reactor.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/generic_models/unit_models/separator.py
  idaes/generic_models/unit_models/stoichiometric_reactor.py
  idaes/generic_models/unit_models/translator.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/column.py
  idaes/power_generation/unit_models/balance.py
  idaes/power_generation/unit_models/boiler_fireside.py
  idaes/power_generation/unit_models/boiler_heat_exchanger.py
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/power_generation/unit_models/downcomer.py
  idaes/power_generation/unit_models/drum.py
  idaes/power_generation/unit_models/drum1D.py
  idaes/power_generation/unit_models/feedwater_heater_0D.py
  idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py
  idaes/power_generation/unit_models/heat_exchanger_3streams.py
  idaes/power_generation/unit_models/helm/mixer.py
  idaes/power_generation/unit_models/helm/splitter.py
  idaes/power_generation/unit_models/steamheater.py
  idaes/power_generation/unit_models/waterpipe.py
  idaes/power_generation/unit_models/watertank.py
  idaes/power_generation/unit_models/waterwall_section.py
  setup.py
Labels: Priority:Low, core, dependencies

#504 Removing deprecated features
  docs/technical_specs/model_libraries/generic/control/pid.rst
  idaes/apps/caprese/examples/cstr_model.py
  idaes/core/components.py
  idaes/core/flowsheet_model.py
  idaes/core/property_base.py
  idaes/core/property_meta.py
  idaes/core/reaction_base.py
  idaes/core/tests/test_components.py
  idaes/core/tests/test_control_volume_0d.py
  idaes/core/tests/test_control_volume_base.py
  idaes/core/tests/test_flowsheet_model.py
  idaes/core/tests/test_property_base.py
  idaes/core/tests/test_reaction_base.py
  idaes/core/tests/test_unit_model.py
  idaes/core/util/tests/test_initialization.py
  idaes/core/util/tests/test_pid_initialization.py
  idaes/dmf/propindex.py
  idaes/dmf/tests/for_propindex.py
  idaes/dmf/tests/test_propindex.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
  idaes/generic_models/properties/cubic_eos/tests/test_cubic_prop_pack.py
  idaes/generic_models/unit_models/tests/test_mixer.py
  idaes/generic_models/unit_models/tests/test_separator.py
  idaes/power_generation/unit_models/helm/tests/test_condenser_ntu.py
  idaes/power_generation/unit_models/helm/tests/test_turbine_inlet.py
  idaes/power_generation/unit_models/helm/tests/test_turbine_outlet.py
Labels: Priority:Normal, core, property packages

#511 Adding set_value method to GeneralVarLikeExpression
  idaes/core/util/misc.py
  idaes/core/util/tests/test_misc.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
Labels: bug, Priority:Normal, core

#514 Fixing deprecation warning about using cardinal indices on Pyomo Sets
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
Labels: Priority:Normal, property packages

#515 Standardize Gen1 column model (Part 1)
  docs/technical_specs/model_libraries/power_generation/carbon_capture/mea_solvent_system/unit_models/phe.rst
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/liquid_prop.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/column.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/plate_heat_exchanger.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_plate_heat_exchanger.py
Labels: enhancement, Priority:High, unit models

#528 Fixing deprecation warning for get_default_solver
  idaes/core/util/testing.py
Labels: bug, Priority:High, core

#465 Adding units to stream_table
  idaes/core/util/tables.py
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/stream_table.js
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
Labels: Priority:High
