Repository IDAES/idaes-pse, pull requests merged in 2021-07, with the labels that each got.

#408 Pin pylint version used in CI checks to avoid unexpected check failures
  .github/actions/pylint/action.yml
  .pylint/idaes_transform.py
  requirements-dev.txt
Labels: Priority:High

#387 Minor gas turbine updates for different gas comp
  idaes/power_generation/flowsheets/gas_turbine/gas_turbine.py
Labels: Priority:High

#336 Generic unit for surrogate models or custom models
  docs/technical_specs/model_libraries/generic/unit_models/index.rst
  docs/technical_specs/model_libraries/generic/unit_models/skeleton_unit.rst
  idaes/generic_models/unit_models/__init__.py
  idaes/generic_models/unit_models/skeleton_model.py
  idaes/generic_models/unit_models/tests/test_skeleton_unit_model.py
Labels: Priority:Normal

#409 HX1D: updting linter errors and removing old pytest markers
  idaes/generic_models/unit_models/heat_exchanger_1D.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger_1D.py
Labels: Priority:Low

#415 Improvements to Properties Interrogator
  docs/technical_specs/model_libraries/generic/property_models/interrogator.rst
  idaes/core/components.py
  idaes/core/phases.py
  idaes/generic_models/properties/interrogator/properties_interrogator.py
  idaes/generic_models/properties/interrogator/reactions_interrogator.py
  idaes/generic_models/properties/interrogator/tests/test_properties_interrogator.py
  idaes/generic_models/properties/interrogator/tests/test_reactions_interrogator.py
Labels: Priority:Normal, enhancement, property packages

#410 Stop using deprecated ConfigEnum class in Caprese
  idaes/apps/caprese/common/config.py
Labels: Priority:Normal

#382 Add check in pytest to enforce that tests have required markers
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
  idaes/conftest.py
  idaes/tests/test_headers.py
  idaes/tests/test_tests.py
Labels: Priority:Normal, testing

#391 Visualizer fails on some flowsheets
  idaes/core/process_base.py
  idaes/core/process_block.py
  idaes/ui/flowsheet.py
  idaes/ui/tests/__init__.py
  idaes/ui/tests/shared.py
  idaes/ui/tests/test_flowsheet.py
Labels: Priority:Normal, bug, flowsheet viewer

#398 Adding support for Henry's Law components
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_vle.py
  idaes/generic_models/properties/core/generic/utility.py
  idaes/generic_models/properties/core/phase_equil/bubble_dew.py
  idaes/generic_models/properties/core/phase_equil/henry.py
  idaes/generic_models/properties/core/phase_equil/smooth_VLE.py
  idaes/generic_models/properties/core/phase_equil/tests/test_henry.py
Labels: Priority:Normal, enhancement, property packages

#417 Adding methods for constant solid properties
  docs/user_guide/components/property_package/general/pure/ConstantProperties.rst
  idaes/generic_models/properties/core/pure/ConstantProperties.py
  idaes/generic_models/properties/core/pure/tests/test_ConstantProperties.py
Labels: Priority:Normal, enhancement, property packages

#419 Adding support for osmotic pressure in generic properties
  docs/user_guide/conventions.rst
  idaes/core/components.py
  idaes/core/phases.py
  idaes/core/tests/test_components.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:Normal, enhancement, property packages

#431 Fixing some bare Exceptions
  idaes/generic_models/properties/interrogator/properties_interrogator.py
  idaes/generic_models/properties/interrogator/tests/test_properties_interrogator.py
Labels: Priority:Normal, bug

#433 Expanding Generic Property Framework
  idaes/core/components.py
  idaes/core/phases.py
  idaes/core/tests/test_phases.py
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_utility.py
  idaes/generic_models/properties/core/generic/utility.py
Labels: Priority:High, enhancement, property packages

#423 Adding tests methods to the capital costing framework (NGCC power plant capital costing)
  idaes/power_generation/costing/tests/test_NGCC_costing.py
Labels: Priority:Normal

#440 Address CI build errors (#439)
  .github/actions/build-docs/action.yml
  .github/actions/pylint/action.yml
  .github/actions/pytest/action.yml
  .github/actions/run-examples/action.yml
  .github/actions/setup-idaes/action.yml
  .github/workflows/core.yml
  .github/workflows/integration.yml
  idaes/config.py
  setup.py
Labels: Priority:High

#348 Utility minimization
  docs/technical_specs/core/util/index.rst
  docs/technical_specs/core/util/utility_minimization.rst
  idaes/core/util/tests/test_utility_minimization.py
  idaes/core/util/utility_minimization.py
Labels: Priority:Normal

#426 Fix execute on load with uncertainty_propagation examples
  idaes/apps/uncertainty_propagation/examples/simple_opt_problem.py
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_NRTL.py
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_rooney.py
Labels: Priority:High

#438 changing generic dictionaries to avoid module warning in examples-pse
  idaes/generic_models/properties/core/examples/CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/examples/HC_PR.py
  idaes/generic_models/properties/core/examples/HC_PR_vap.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
Labels: Priority:Normal
