Repository IDAES/idaes-pse, pull requests merged in 2021-12, with the labels that each got.

#588 Entropy fix, partial molar properties, and log mole fractions
  idaes/core/util/tests/test_phase_equilibria.py
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
  idaes/generic_models/properties/core/eos/tests/test_haber_bosch_validation_PR.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/generic_models/unit_models/tests/test_heater.py
  idaes/power_generation/flowsheets/gas_turbine/gas_turbine.py
  idaes/power_generation/flowsheets/gas_turbine/tests/test_gas_turbine.py
  idaes/power_generation/flowsheets/test/test_NGFC.py
  idaes/power_generation/properties/tests/test_NG_PR.py
Labels: Priority:High

#619 Fixing some inter-dependency between component and unit tests
  idaes/generic_models/properties/core/generic/tests/test_vle.py
  idaes/generic_models/unit_models/tests/test_skeleton_unit_model.py
  idaes/power_generation/costing/tests/test_NGCC_costing.py
Labels: Priority:Normal, testing

#622 Fixing some Pyomo warnings
  docs/technical_specs/core/util/model_serializer.rst
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/unit_models/column_models/tests/test_solvent_condenser.py
Labels: bug, Priority:Normal

#618 Adding Exception for models to raise if initialization fails
  idaes/core/util/exceptions.py
  idaes/core/util/tests/test_exceptions.py
  idaes/generic_models/properties/activity_coeff_models/activity_coeff_prop_pack.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py
  idaes/generic_models/properties/cubic_eos/tests/test_BT_example.py
  idaes/generic_models/properties/tests/test_harness.py
  idaes/generic_models/properties/tests/test_iapws95_with_harness.py
  idaes/generic_models/properties/tests/test_swco2_with_harness.py
Labels: enhancement, Priority:Normal, core, property packages

#621 Improving docs for stoichiometric reactor
  docs/technical_specs/model_libraries/generic/unit_models/stoichiometric_reactor.rst
Labels: documentation, Priority:Normal, unit models

#628 Omlt integration
  idaes/commands/tests/test_commands.py
  idaes/surrogate/alamopy.py
  idaes/surrogate/base/surrogate_base.py
  idaes/surrogate/keras_surrogate.py
  idaes/surrogate/sampling/__init__.py
  idaes/surrogate/sampling/data_utils.py
  idaes/surrogate/sampling/scaling.py
  idaes/surrogate/sampling/tests/test_scaling.py
  idaes/surrogate/surrogate_block.py
  idaes/surrogate/tests/data/PT_data.csv
  idaes/surrogate/tests/data/T_data.csv
  idaes/surrogate/tests/data/create_keras_models.py
  idaes/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.h5
  idaes/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.json
  idaes/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.h5
  idaes/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.json
  idaes/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.h5
  idaes/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.json
  idaes/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.h5
  idaes/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.json
  idaes/surrogate/tests/test_keras_surrogate.py
  setup.py
Labels: Priority:High

#630 Visualizer use saved layout by default
  idaes/ui/fsvis/fsvis.py
  idaes/ui/fsvis/tests/test_fsvis.py
Labels: Priority:High, flowsheet viewer, ui

#625 Update extensions version
  idaes/config.py
Labels: Priority:High

#631 Temporarily skip failing integration test to address #493
  idaes/commands/tests/test_commands.py
Labels: Priority:High

#636 Making tensorflow optional in test_keras_surrogate
  idaes/surrogate/keras_surrogate.py
  idaes/surrogate/tests/test_keras_surrogate.py
  setup.py
Labels: Priority:High

#626 Fix two bugs in model serializer.
  idaes/core/util/model_serializer.py
  idaes/core/util/tests/test_model_serializer.py
Labels: bug, Priority:Normal

#416 Test property constraints in CLC oxidation property package
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/gas_phase_thermo.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_gas_prop.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_rxn_prop.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_solid_prop.py
Labels: Priority:Normal

#582 Generalized Packed Column
  idaes/generic_models/unit_models/column_models/solvent_column.py
  idaes/generic_models/unit_models/column_models/tests/test_solvent_column.py
Labels: Priority:High

#494 Adding encoding to the file read of the index file
  idaes/ui/fsvis/model_server.py
Labels: Priority:Normal

#598 Flowsheet Visualizer: Multi connections for the mixer component as a 'target' model
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/js/cell_config.js
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/icons.py
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
  idaes/ui/tests/test_flowsheet.py
  idaes/ui/tests/test_icons.py
Labels: Priority:High, ui

#617 Minor correction in MEA solvent property package
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/tests/test_mea_solvent.py
Labels: bug, Priority:Normal, property packages

#611 Ensuring ignore_constraint_scaling is enforced for Jacobian autoscaler
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
Labels: Priority:High
