Repository IDAES/idaes-pse, pull requests merged in 2021-06, with the labels that each got.

#358 This adds a utiliy to use WSL to run solvers for Linux on Windows
  idaes/commands/wrap_solver_wsl.py
Labels: Priority:Normal

#364 Adding a method to compute heat capacity ratio in generic property pack
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:Normal, enhancement, property packages

#365 Adding solid properties to ideal eos
  idaes/core/components.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
Labels: Priority:Normal, enhancement, property packages

#377 Bumping the pyomo dependency to Pyomo 6.0.1 (rc1)
  setup.py
Labels: Priority:High

#360 Adding prototype solubility product formulation
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/equilibrium_forms.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_forms.py
  idaes/generic_models/properties/core/reactions/tests/test_solubility_product_verification.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
Labels: Priority:Normal, enhancement, property packages

#374 Fix issue where there are no extraction splits
  idaes/power_generation/unit_models/helm/turbine_multistage.py
Labels: Priority:High

#376 Fix separator scale factor calcs
  idaes/generic_models/unit_models/separator.py
  idaes/generic_models/unit_models/tests/test_flash.py
  idaes/generic_models/unit_models/tests/test_separator.py
Labels: Priority:High, bug

#378 Verifying eNRTL model for two-salt system
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/enrtl_parameters.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_KCl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl_KCl.py
Labels: Priority:Normal, enhancement, property packages, testing

#58 Address all pylint errors in the current codebase
  .github/actions/pylint/action.yml
  .pylint/idaes_reporters.py
  .pylint/idaes_transform.py
  .pylint/pylintrc
  .pylint/render_report.py
  idaes/commands/base.py
  idaes/core/process_base.py
  idaes/core/process_block.py
  idaes/core/property_base.py
  idaes/core/property_meta.py
  idaes/core/reaction_base.py
  idaes/core/tests/test_control_volume_base.py
  idaes/core/util/convergence/convergence_base.py
  idaes/core/util/convergence/mpi_utils.py
  idaes/core/util/dyn_utils.py
  idaes/core/util/unit_costing.py
  idaes/dmf/commands.py
  idaes/dmf/magics.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/enrtl_parameters.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/logger.py
  idaes/power_generation/flowsheets/gas_turbine/gas_turbine.py
  idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
  idaes/power_generation/unit_models/boiler_fireside.py
  idaes/power_generation/unit_models/helm/condenser_ntu.py
  idaes/power_generation/unit_models/helm/mixer.py
  idaes/surrogate/alamopy/allcard.py
  idaes/surrogate/alamopy/doalamo.py
  idaes/surrogate/helmet/BasisFunctions.py
  idaes/surrogate/helmet/GAMSDataWrite.py
  idaes/surrogate/helmet/Helmet.py
  idaes/surrogate/main.py
  idaes/surrogate/my_surrogate_base.py
  idaes/surrogate/pysmo/polynomial_regression.py
  idaes/surrogate/ripe/__init__.py
  idaes/surrogate/ripe/read.py
  idaes/surrogate/ripe/write.py
Labels: Priority:High

#381 Adding ideal properties to eNRTL model
  idaes/core/property_base.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:Normal, bug, property packages

#394 Correcting unsymmetric reference state to be near-zero instead of zero
  idaes/generic_models/properties/core/eos/enrtl_reference_states.py
Labels: Priority:High, bug, property packages

#388 MatOpt documentation update
  docs/user_guide/modeling_extensions/matopt/index.rst
Labels: Priority:Normal

#395 Fix errors due to missing json.gz and dat files when installing IDAES not in editable mode
  setup.py
Labels: Priority:High

#397 Adding .VSCode directories to .gitignore
  .gitignore
Labels: Priority:Normal, enhancement

#399 Making time a property of flowsheets
  idaes/core/flowsheet_model.py
  idaes/core/tests/test_flowsheet_model.py
Labels: Priority:Normal, core, enhancement
