Repository IDAES/idaes-pse, pull requests merged in 2021-05, with the labels that each got.

#131 uncertainty_propagation
  docs/user_guide/modeling_extensions/index.rst
  docs/user_guide/modeling_extensions/uncertainty_propagation/index.rst
  idaes/apps/uncertainty_propagation/examples/BT_NRTL_dataset.csv
  idaes/apps/uncertainty_propagation/examples/NRTL_model_scripts.py
  idaes/apps/uncertainty_propagation/examples/README.md
  idaes/apps/uncertainty_propagation/examples/rooney_biegler.py
  idaes/apps/uncertainty_propagation/examples/simple_opt_problem.py
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_NRTL.ipynb
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_NRTL.py
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_rooney.ipynb
  idaes/apps/uncertainty_propagation/examples/uncertainty_propagation_rooney.py
  idaes/apps/uncertainty_propagation/sens.py
  idaes/apps/uncertainty_propagation/tests/BT_NRTL_dataset.csv
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
  idaes/apps/uncertainty_propagation/uncertainties.py
Labels: Priority:High

#307 First pass at FAQ page in docs
  docs/faq.rst
  docs/index.rst
Labels: Priority:Normal

#298 Filling missing stream table entries with placeholder
  idaes/core/util/tables.py
  idaes/ui/flowsheet.py
  idaes/ui/tests/serialized_boiler_flowsheet.json
Labels: Priority:Normal, core

#324 Added jumpovers when lines overlap
  idaes/ui/flowsheet.py
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
Labels: Priority:Normal

#317 Update model data warning test
  idaes/dmf/tests/test_model_data.py
Labels: Priority:Normal

#329 Helmholtz thermo expr for v fix mw
  idaes/generic_models/properties/helmholtz/helmholtz.py
Labels: Priority:Normal

#315 Add utilities for scaled Jacobian and condition number
  docs/technical_specs/core/util/scaling.rst
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
Labels: Priority:Normal

#333 Using named Expressions in Generic Properties
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/properties/core/reactions/equilibrium_forms.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
  idaes/generic_models/properties/cubic_eos/BT_PR.py
  idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py
Labels: Priority:Normal, bug, property packages

#334 Fixing issue with units in the equilibrium_constant module
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
Labels: Priority:Normal, bug, property packages

#331 Adding first verification tests for eNRTL model
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl_verification_NaCl.py
Labels: Priority:Normal, property packages, testing

#339 Fixing some issues with indexing sets in generic properties
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:High, bug, property packages

#292 Refactor setup.py and requirements-dev.txt to streamline installation workflows
  .github/actions/pylint/action.yml
  .github/actions/setup-idaes/action.yml
  README.md
  docs/advanced_user_guide/advanced_install/index.rst
  docs/getting_started/index.rst
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
  idaes/config.py
  idaes/dmf/tests/util.py
  idaes/surrogate/pysmo/tests/test_kriging.py
  idaes/surrogate/pysmo/tests/test_polynomial_regression.py
  idaes/surrogate/pysmo/tests/test_radial_basis_function.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Priority:High

#316 Update install docs.
  docs/getting_started/index.rst
Labels: Priority:Normal

#326 Context manager for temprary config changes
  idaes/__init__.py
  idaes/config.py
  idaes/core/solvers.py
  idaes/tests/test_config.py
  idaes/tests/test_ipopt.py
Labels: Priority:Normal

#342 Updates for Pyomo 6 compatibility
  idaes/core/util/model_statistics.py
  idaes/core/util/tests/test_dyn_utils.py
  idaes/core/util/tests/test_misc.py
  idaes/core/util/tests/test_model_statistics.py
  idaes/core/util/tests/test_phase_equilibria.py
  idaes/generic_models/control/tests/test_steam_tank.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/reactions/tests/test_rate_forms.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
  idaes/generic_models/properties/examples/tests/test_saponification_thermo.py
  idaes/generic_models/properties/tests/test_iapws95.py
  idaes/generic_models/unit_models/tests/test_separator.py
Labels: Priority:High, bug

#347 Adding initial overwrite option to constraint_scaling_transformation
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
  idaes/core/util/unit_costing.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/phase_equil/bubble_dew.py
  idaes/generic_models/properties/core/phase_equil/smooth_VLE.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/electrolyte_states.py
  idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py
  idaes/generic_models/unit_models/heat_exchanger.py
  idaes/generic_models/unit_models/heat_exchanger_1D.py
  idaes/generic_models/unit_models/mixer.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/properties/flue_gas_ideal.py
  idaes/power_generation/unit_models/boiler_fireside.py
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/power_generation/unit_models/downcomer.py
  idaes/power_generation/unit_models/drum.py
  idaes/power_generation/unit_models/drum1D.py
  idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py
  idaes/power_generation/unit_models/heat_exchanger_3streams.py
  idaes/power_generation/unit_models/helm/compressor.py
  idaes/power_generation/unit_models/helm/condenser_ntu.py
  idaes/power_generation/unit_models/helm/mixer.py
  idaes/power_generation/unit_models/helm/pump.py
  idaes/power_generation/unit_models/helm/splitter.py
  idaes/power_generation/unit_models/helm/turbine.py
  idaes/power_generation/unit_models/helm/turbine_inlet.py
  idaes/power_generation/unit_models/helm/turbine_multistage.py
  idaes/power_generation/unit_models/helm/turbine_outlet.py
  idaes/power_generation/unit_models/helm/valve_steam.py
  idaes/power_generation/unit_models/steamheater.py
  idaes/power_generation/unit_models/waterwall_section.py
Labels: Priority:Normal, enhancement

#350 Standardising distillation tests
  idaes/generic_models/unit_models/distillation/tests/test_conventional_tray.py
  idaes/generic_models/unit_models/distillation/tests/test_feed_tray.py
  idaes/generic_models/unit_models/distillation/tests/test_partial_condenser.py
  idaes/generic_models/unit_models/distillation/tests/test_reboiler.py
  idaes/generic_models/unit_models/distillation/tests/test_total_condenser.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_column.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_side_liq_draw.py
  idaes/generic_models/unit_models/distillation/tests/test_tray_side_vap_draw.py
Labels: Priority:Normal, testing

#228 Improve save_as option for visualize()
  docs/conf.py
  docs/user_guide/vis/index.rst
  idaes/dmf/codesearch.py
  idaes/surrogate/pysmo/polynomial_regression.py
  idaes/ui/fsvis/__init__.py
  idaes/ui/fsvis/errors.py
  idaes/ui/fsvis/fsvis.py
  idaes/ui/fsvis/model_server.py
  idaes/ui/fsvis/persist.py
  idaes/ui/fsvis/tests/test_fsvis.py
  idaes/ui/fsvis/tests/test_model_server.py
  idaes/ui/fsvis/tests/test_persist.py
Labels: Priority:Normal, enhancement, flowsheet viewer

#354 Updating pyomo to the 6.0.rc1 tag, removing PyUtilib dependency
  docs/user_guide/logging.rst
  idaes/apps/caprese/nmpc.py
  idaes/apps/matopt/opt/mat_modeling.py
  idaes/core/plugins/simple_equality_eliminator.py
  idaes/core/plugins/variable_replace.py
  idaes/core/util/convergence/convergence_base.py
  idaes/core/util/convergence/tests/test_convergence.py
  idaes/core/util/misc.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR.py
  idaes/generic_models/properties/core/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_H2O_Ideal_VLE.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
  idaes/logger.py
  idaes/surrogate/pysmo/tests/test_sampling_modified.py
  idaes/surrogate/pysmo/tests/test_utils.py
  idaes/util/update_workshop_materials.py
  scripts/workshops/update_workshop_materials.py
  setup.py
Labels: Priority:High

#353 Minor gas turbine fixes
  idaes/power_generation/flowsheets/gas_turbine/gas_turbine.py
Labels: Priority:Normal

#357 Fixing some pytest marks
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_HC_PR_vap.py
Labels: Priority:Low, testing

#351 Command line config tools
  docs/user_guide/configuration.rst
  idaes/__init__.py
  idaes/commands/__init__.py
  idaes/commands/base.py
  idaes/commands/config.py
  idaes/commands/convergence.py
  idaes/commands/examples.py
  idaes/commands/tests/test_commands.py
  idaes/config.py
Labels: Priority:Normal

#320 Pinned Variable column to the left of the stream table
  idaes/ui/fsvis/static/js/stream_table.js
Labels: Priority:Normal

#359 Use Ubuntu 18.04 binaries on all release from 18.04 to 19.10
  idaes/config.py
Labels: Priority:Normal

#363 Ignoring Mac OSX's .DS_Store
  .gitignore
Labels: Priority:Normal

#252 Get version and git hash of a module
  idaes/dmf/__init__.py
  idaes/dmf/getver.py
  idaes/dmf/tests/test_getver.py
Labels: Priority:Normal

#325 Update README
  README.md
Labels: Priority:Normal, documentation

#345 Export flowsheet to SVG minor changes
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/toolbar.js
Labels: Priority:Normal

#319 Use 'addheader' instead of script in repo
  COPYRIGHT.md
  addheader.yml
  idaes/tests/test_headers.py
  requirements-dev.txt
  scripts/annotate_source
Labels: Priority:High
