Repository IDAES/idaes-pse, pull requests merged in 2021-04, with the labels that each got.

#277 Adds reference link (DOI) for Amine units
  docs/technical_specs/model_libraries/power_generation/carbon_capture/mea_solvent_system/unit_models/column.rst
Labels: Priority:Low, documentation

#274 Fix mixer init logging
  idaes/generic_models/unit_models/mixer.py
Labels: Priority:Normal, bug

#260 Add MIME type for returned local JS modules
  idaes/ui/fsvis/model_server.py
Labels: Priority:High, flowsheet viewer

#279 Fixing unit consistency issue in Gibbs Energy form for Keq
  docs/user_guide/components/property_package/general_reactions/equil_constant.rst
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
Labels: Priority:Low, bug, property packages

#249 Attaching dangling References to models and tests for cloning models
  .github/actions/run-examples/build-config-for-idaes-ci.yml
  .github/actions/setup-idaes/action.yml
  .github/workflows/core.yml
  idaes/core/unit_model.py
  idaes/generic_models/unit_models/distillation/tray.py
  idaes/generic_models/unit_models/tests/test_valve.py
  idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
  idaes/tests/test_clone_model.py
Labels: Priority:High, bug

#288 4 bug fixes
  idaes/core/components.py
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/tests/test_components.py
  idaes/core/unit_model.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/phase_equil/forms.py
  idaes/generic_models/properties/core/pure/RPP5.py
  idaes/generic_models/properties/core/reactions/dh_rxn.py
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
Labels: Priority:High, bug, core, property packages

#284 ENRTL Model Part 1
  idaes/core/__init__.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/enrtl_submethods.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:Normal, enhancement, property packages

#164 Supercritical CO2 compressor
  idaes/power_generation/carbon_capture/compression_system/compressor.py
  idaes/power_generation/carbon_capture/compression_system/tests/test_compressor.py
Labels: Priority:Normal, unit models

#291 Fixing bug with creating phase-component set in Generic Properties
  idaes/generic_models/properties/core/generic/generic_property.py
Labels: Priority:Normal, bug, property packages

#290 eNRTL Model Part 2
  idaes/core/components.py
  idaes/core/util/constants.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/enrtl_parameters.py
  idaes/generic_models/properties/core/eos/enrtl_reference_states.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/properties/core/generic/tests/test_electrolyte_components.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
  idaes/generic_models/properties/core/phase_equil/tests/test_bubble_dew.py
  idaes/generic_models/properties/core/pure/electrolyte.py
  idaes/generic_models/properties/core/pure/tests/test_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP_electrolyte.py
Labels: Priority:Normal, enhancement, property packages

#264 Replaced numpy nans with string NaN
  idaes/ui/flowsheet.py
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/test_flowsheet.py
Labels: Priority:High

#257 Add more debug logging to solver download.
  idaes/commands/extensions.py
  idaes/commands/tests/test_commands.py
  idaes/util/download_bin.py
Labels: Priority:High
