Repository IDAES/idaes-pse, pull requests merged in 2021-03, with the labels that each got.

#234 Add section on installing IDAES using Conda to installation docs
  docs/getting_started/index.rst
Labels: Priority:High, documentation, enhancement

#238 Fix command "get-examples" test failures
  idaes/commands/examples.py
  idaes/commands/tests/test_commands.py
Labels: Priority:High

#230 Removing unnecessary constraint terms in 1D control volumes
  idaes/apps/caprese/tests/test_nmpc_var.py
  idaes/apps/caprese/tests/test_simple_model.py
  idaes/apps/matopt/tests/test_matopt_objects_functionality.py
  idaes/core/control_volume1d.py
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/moving_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
  idaes/gas_solid_contactors/unit_models/tests/test_MB.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property_integration.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
  idaes/generic_models/properties/cubic_eos/tests/test_cubic_root.py
  idaes/generic_models/unit_models/tests/test_pfr.py
  idaes/ui/tests/test_flowsheet.py
Labels: Priority:Normal, bug, unit models

#237 Adding scaling support to generic properties framework
  idaes/core/property_meta.py
  idaes/core/util/phase_equilibria.py
  idaes/core/util/scaling.py
  idaes/generic_models/properties/core/eos/ceos.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/eos/eos_base.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/dummy_eos.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/generic/utility.py
  idaes/generic_models/properties/core/phase_equil/bubble_dew.py
  idaes/generic_models/properties/core/phase_equil/forms.py
  idaes/generic_models/properties/core/phase_equil/smooth_VLE.py
  idaes/generic_models/properties/core/phase_equil/tests/test_forms.py
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP.py
  idaes/generic_models/properties/cubic_eos/cubic_prop_pack.py
Labels: Priority:Normal, enhancement, property packages

#239 Minor update to copy_port_values(), now can take and arc
  idaes/core/util/misc.py
  idaes/core/util/tests/test_misc.py
Labels: Priority:Normal

#242 Mark bin download test as integration
  idaes/util/tests/test_download_bin.py
Labels: Priority:Normal, testing

#241 Adding initial support for true and apparent compositions in generic properties
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/property_base.py
  idaes/core/tests/test_control_volume_0d.py
  idaes/core/tests/test_control_volume_1d.py
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/generic/tests/test_electrolyte_components.py
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/equilibrium_forms.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_forms.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/electrolyte_states.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx_electrolyte.py
Labels: Priority:Normal, enhancement, property packages

#55 Control volume scaling
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/control_volume_base.py
  idaes/core/reaction_base.py
  idaes/core/tests/test_control_volume_0d_scaling.py
  idaes/core/tests/test_control_volume_1d_scaling.py
  idaes/core/util/scaling.py
  idaes/core/util/testing.py
Labels: Priority:High, core

#231 Convergence Tester Update
  idaes/__init__.py
  idaes/commands/convergence.py
  idaes/commands/tests/test_commands.py
  idaes/convergence/__init__.py
  idaes/convergence/generic_models/__init__.py
  idaes/convergence/generic_models/pressure_changer.py
  idaes/convergence/power_generation/__init__.py
  idaes/convergence/power_generation/compressor.py
  idaes/convergence/power_generation/heater.py
  idaes/convergence/power_generation/turbine.py
  idaes/core/util/convergence/convergence.py
  idaes/core/util/convergence/convergence_base.py
  idaes/core/util/convergence/tests/test_convergence.py
  idaes/generic_models/unit_models/convergence/__init__.py
  idaes/generic_models/unit_models/convergence/pressure_changer/PressureChanger-10.json
  idaes/generic_models/unit_models/convergence/pressure_changer/PressureChanger_Reliability_Testing_Specification.xlsx
  idaes/generic_models/unit_models/convergence/pressure_changer/__init__.py
  idaes/power_generation/unit_models/helm/convergence/__init__.py
  idaes/power_generation/unit_models/helm/convergence/readme.txt
  idaes/power_generation/unit_models/helm/tests/test_compare_to_generic.py
Labels: Priority:Normal

#235 Updating SCPC steam cycle
  idaes/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
  idaes/power_generation/flowsheets/test/test_scsc.py
Labels: Priority:Normal

#251 Patch for initializing moving bed reaction generation variables
  idaes/gas_solid_contactors/unit_models/moving_bed.py
Labels: Priority:Normal, unit models

#261 Fixing bug in control volume scaling
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/tests/test_control_volume_0d_scaling.py
  idaes/core/tests/test_control_volume_1d_scaling.py
Labels: Priority:High, bug

#256 Adding scaling to generic reaction framework
  idaes/core/reaction_base.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/examples/tests/test_CO2_bmimPF6_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/generic_reaction.py
  idaes/generic_models/properties/core/generic/tests/test_generic_reaction.py
  idaes/generic_models/properties/core/reactions/dh_rxn.py
Labels: Priority:Normal, enhancement, property packages

#262 Add addtional flow expressions to generic properties
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
Labels: Priority:High

#265 Adding support for electrolytes with FPhx states
  idaes/generic_models/properties/core/eos/enrtl.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FPhx.py
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcTP.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/generic/tests/test_generic_property.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP_electrolyte.py
Labels: Priority:Normal, enhancement, property packages

#267 Moving some slow tests to integration
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/tests/test_column.py
  idaes/power_generation/flowsheets/test/test_NGFC.py
  idaes/power_generation/properties/tests/test_SOFC_ROM.py
Labels: Priority:Low, testing

#266 Update the binaries version to pick up a recent k_aug change.
  idaes/config.py
Labels: Priority:High

#268 Adding support for more state definitions with electrolytes
  idaes/generic_models/properties/core/examples/tests/test_BTIdeal_FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP_electrolyte.py
Labels: Priority:Normal, enhancement, property packages

#269 Add performace curve structure to isentropic pressure changers.
  docs/technical_specs/model_libraries/generic/unit_models/pressure_changer.rst
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/generic_models/unit_models/tests/test_pressure_changer.py
Labels: Priority:High

#270 Correcting equation in documentation
  docs/user_guide/components/property_package/general/pure/NIST.rst
Labels: Priority:Normal, documentation

#271 Final (hopefully) steps in setting up infrastructure for electrolytes
  docs/user_guide/components/property_package/general_reactions/equil_constant.rst
  docs/user_guide/components/property_package/general_reactions/equil_form.rst
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/generic_models/properties/core/reactions/equilibrium_constant.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
  idaes/generic_models/properties/core/state_definitions/FPhx.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/FcPh.py
  idaes/generic_models/properties/core/state_definitions/FcTP.py
  idaes/generic_models/properties/core/state_definitions/FpcTP.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FPhx_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcPh_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FcTP_electrolyte.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FpcTP_electrolyte.py
Labels: Priority:Normal, enhancement, property packages

#207 SolverFactory Wrapper
  docs/user_guide/configuration.rst
  idaes/config.py
  idaes/core/plugins/__init__.py
  idaes/core/plugins/solvers.py
  idaes/core/solvers.py
  idaes/core/util/misc.py
  idaes/core/util/tests/test_homotopy.py
  idaes/tests/test_config.py
  idaes/tests/test_ipopt.py
Labels: Priority:High

#276 Handling mismatched true and apparent species in generic reaction framework
  idaes/generic_models/properties/core/generic/generic_reaction.py
Labels: Priority:Low, bug, property packages
