Repository IDAES/idaes-pse, pull requests merged in 2022-12, with the labels that each got.

#1034 Add support for optional activation of v1 compatibility mode
  .github/workflows/v1-compat.yml
  idaes/__init__.py
  idaes/apps/roundingRegression/__init__.py
  idaes/core/ui/icons/__init__.py
  idaes/models_extra/carbon_capture/__init__.py
  idaes/models_extra/carbon_capture/co2_compressor.py
Labels: Priority:High, backward-compat

#1041 Update import paths deprecated in Pyomo 6.4.3
  idaes/core/util/tests/test_scaling.py
Labels: Priority:High

#1049 Fixing print statement in SurrogateBlock
  idaes/core/surrogate/surrogate_block.py
Labels: bug, Priority:High, surrogates

#1047 Add MomentumBalanceType config for Separator Unit
  docs/reference_guides/model_libraries/generic/unit_models/separator.rst
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/tests/test_separator.py
Labels: enhancement, user request, Priority:Normal, unit models

#1053 Function to find unused variables
  idaes/core/util/model_statistics.py
  idaes/core/util/tests/test_model_statistics.py
Labels: enhancement, Priority:Normal, core

#1052 Add 2021 CEPCI Value
  idaes/core/base/costing_base.py
  idaes/core/base/tests/test_costing_base.py
Labels: Priority:Normal

#1057 Fix typo in model development documentation
  docs/how_to_guides/custom_models/unit_model_development.rst
Labels: documentation, Priority:Low
