Repository IDAES/idaes-pse, pull requests merged in 2022-05, with the labels that each got.

#813 Nonisothermal solid oxide cell model
  idaes/models_extra/power_generation/unit_models/soc_submodels/__init__.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/common.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/contact_resistor.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/porous_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_cell.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_module_simple.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/testing.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/case_1.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/case_2.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/case_3.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/case_4.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/case_5.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/herring-et-al-data.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/data_cache/sweep_5_kazempoor_replication.csv
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_common.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_contact_resistor.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_porous_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_solid_oxide_cell.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_triple_phase_boundary.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/triple_phase_boundary.py
Labels: enhancement, Priority:High, unit models

#812 Removing old DMF code related to tabular data and property indexing
  data/config.yaml
  idaes/dmf/__init__.py
  idaes/dmf/dmfbase.py
  idaes/dmf/propdata.py
  idaes/dmf/propindex.py
  idaes/dmf/tabular.py
  idaes/dmf/tests/test_propdata.py
  idaes/dmf/tests/test_propdata_csv.py
  idaes/dmf/tests/test_propindex.py
  idaes/dmf/tests/test_resource.py
  idaes/dmf/tests/test_tabular.py
  idaes/dmf/userapi.py
Labels: Priority:High, dmf

#833 CLC Oxidation Property Updates
  idaes/core/base/property_meta.py
  idaes/models_extra/gas_solid_contactors/flowsheets/ss_BFB_OC_oxidation.py
  idaes/models_extra/gas_solid_contactors/properties/methane_iron_OC_reduction/gas_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/gas_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/hetero_reactions.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/solid_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_gas_prop.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_rxn_prop.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_solid_prop.py
  idaes/models_extra/gas_solid_contactors/unit_models/tests/test_BFB_methane_oc.py
  idaes/models_extra/gas_solid_contactors/unit_models/tests/test_BFB_oxygen_oc.py
  idaes/models_extra/gas_solid_contactors/unit_models/tests/test_MB.py
Labels: Priority:High, testing

#846 Replace hardcoded coefficients with Vars in Henry's constant
  idaes/models_extra/column_models/properties/MEA_solvent.py
Labels: Priority:High, property packages

#821 MEA solvent column model
  idaes/models_extra/column_models/MEAsolvent_column.py
  idaes/models_extra/column_models/properties/MEA_vapor.py
  idaes/models_extra/column_models/properties/tests/test_mea_vapor.py
  idaes/models_extra/column_models/solvent_column.py
  idaes/models_extra/column_models/tests/test_MEAsolvent_column.py
  idaes/models_extra/column_models/tests/test_solvent_column.py
Labels: Priority:High

#854 Configure GHA run serialization to automatically cancel redundant workflow runs
  .github/workflows/core.yml
  .github/workflows/integration.yml
Labels: Priority:High

#848 Adding better testing of unit model report method
  idaes/core/base/process_base.py
  idaes/core/base/tests/test_process_base.py
  idaes/core/base/tests/test_unit_model.py
  idaes/core/ui/tests/demo_flowsheet.json
  idaes/core/ui/tests/flash_flowsheet.json
  idaes/core/ui/tests/serialized_boiler_flowsheet.json
  idaes/models/unit_models/flash.py
  idaes/models/unit_models/heat_exchanger.py
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/tests/test_cstr.py
  idaes/models/unit_models/tests/test_equilibrium_reactor.py
  idaes/models/unit_models/tests/test_feed.py
  idaes/models/unit_models/tests/test_feed_flash.py
  idaes/models/unit_models/tests/test_flash.py
  idaes/models/unit_models/tests/test_gibbs.py
  idaes/models/unit_models/tests/test_heat_exchanger.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_heat_exchanger_lc.py
  idaes/models/unit_models/tests/test_heater.py
  idaes/models/unit_models/tests/test_hx_ntu.py
  idaes/models/unit_models/tests/test_mixer.py
  idaes/models/unit_models/tests/test_pfr.py
  idaes/models/unit_models/tests/test_pressure_changer.py
  idaes/models/unit_models/tests/test_product.py
  idaes/models/unit_models/tests/test_rstoic.py
  idaes/models/unit_models/tests/test_separator.py
  idaes/models/unit_models/tests/test_statejunction.py
  idaes/models/unit_models/tests/test_translator.py
  idaes/models/unit_models/tests/test_valve.py
Labels: Priority:Normal, testing, ui

#847 New Binary Version (More ARM64)
  docs/tutorials/advanced_install/index.rst
  docs/tutorials/getting_started/binaries.rst
  docs/tutorials/getting_started/index.rst
  idaes/config.py
  idaes/core/solvers/tests/test_solvers.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/models_extra/gas_solid_contactors/unit_models/tests/test_BFB_methane_oc.py
  idaes/models_extra/power_generation/flowsheets/test/test_NGFC.py
Labels: Priority:Normal, core

#824 Pass static generator parameters to Prescient from bidder
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/examples/thermal_generator.py
  idaes/apps/grid_integration/model_data.py
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/apps/grid_integration/tests/test_model_data.py
  idaes/apps/grid_integration/tests/test_tracker.py
  idaes/apps/grid_integration/tests/util.py
  idaes/apps/grid_integration/utils.py
Labels: Priority:Low

#823 Add double loop (grid-integration) docs.
  docs/index.rst
  docs/reference_guides/apps/grid_integration/Bidder.rst
  docs/reference_guides/apps/grid_integration/Coordinator.rst
  docs/reference_guides/apps/grid_integration/Implementation.rst
  docs/reference_guides/apps/grid_integration/Introduction.rst
  docs/reference_guides/apps/grid_integration/Tracker.rst
  docs/reference_guides/apps/grid_integration/images/example_bid.png
  docs/reference_guides/apps/grid_integration/images/framework.png
  docs/reference_guides/apps/grid_integration/images/implementation.png
  docs/reference_guides/apps/grid_integration/images/tracking_example.png
  docs/reference_guides/apps/grid_integration/index.rst
  docs/reference_guides/index.rst
  idaes/apps/grid_integration/tracker.py
Labels: documentation, Priority:High

#857 Updating marks on some tests
  idaes/models/properties/cubic_eos/tests/test_BT_example.py
  idaes/models/properties/modular_properties/examples/tests/test_ASU_PR.py
  idaes/models/properties/modular_properties/examples/tests/test_ASU_PR_Dowling_2015.py
  idaes/models/properties/modular_properties/examples/tests/test_BTIdeal.py
  idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FPhx.py
  idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FcPh.py
  idaes/models/properties/modular_properties/examples/tests/test_BTIdeal_FcTP.py
  idaes/models/properties/modular_properties/examples/tests/test_BT_PR.py
  idaes/models/properties/modular_properties/examples/tests/test_HC_PR.py
  idaes/models/properties/tests/test_harness.py
  idaes/models/properties/tests/test_iapws95_with_harness.py
  idaes/models/properties/tests/test_swco2_with_harness.py
  idaes/models_extra/power_generation/costing/tests/test_NGCC_costing.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/tests/test_subcritical_flowsheets.py
Labels: Priority:Normal, testing

#825 Color variable types
  idaes/core/ui/flowsheet.py
  idaes/core/ui/fsvis/static/css/main.css
  idaes/core/ui/fsvis/static/js/stream_table.js
  idaes/core/ui/fsvis/static/lib/backbone/backbone.js
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.js
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.js.map
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.min.js
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.bundle.min.js.map
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.js
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.js.map
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.min.js
  idaes/core/ui/fsvis/static/lib/bootstrap/bootstrap.min.js.map
  idaes/core/ui/fsvis/static/lib/dist/joint.format.svg.min.js
  idaes/core/ui/fsvis/static/lib/dist/rappid.min.js
  idaes/core/ui/fsvis/static/lib/jquery/dist/jquery.js
  idaes/core/ui/fsvis/static/lib/lodash/lodash.min.js
  idaes/core/ui/fsvis/templates/index.html
  idaes/core/ui/tests/demo_flowsheet.json
  idaes/core/ui/tests/flash_flowsheet.json
  idaes/core/ui/tests/serialized_boiler_flowsheet.json
  idaes/core/util/tables.py
  idaes/core/util/tests/test_tables.py
Labels: Priority:Normal

#851 Saving model onchange
  idaes/core/ui/fsvis/fsvis.py
  idaes/core/ui/fsvis/model_server.py
  idaes/core/ui/fsvis/static/js/main.js
  idaes/core/ui/fsvis/static/js/paper.js
  idaes/core/ui/fsvis/static/js/toolbar.js
  idaes/core/ui/fsvis/tests/test_model_server.py
Labels: Priority:High
