Repository IDAES/idaes-pse, pull requests merged in 2022-11, with the labels that each got.

#990 Added extra comments
  idaes/core/ui/fsvis/static/js/cell_config.js
  idaes/core/ui/fsvis/static/js/paper.js
  idaes/core/ui/fsvis/static/js/stream_table.js
  idaes/core/ui/fsvis/static/js/toolbar.js
Labels: documentation, Priority:Low

#1000 Remove old Helmholtz EoS and switch to data files for component definitions.
  idaes/config.py
  idaes/core/ui/tests/demo_flowsheet.json
  idaes/core/ui/tests/serialized_boiler_flowsheet.json
  idaes/core/util/tests/test_model_statistics.py
  idaes/models/properties/general_helmholtz/__init__.py
  idaes/models/properties/general_helmholtz/components/__init__.py
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
  idaes/models/properties/general_helmholtz/helmholtz_state.py
  idaes/models/properties/general_helmholtz/tests/test_functions_unit.py
  idaes/models/properties/general_helmholtz/tests/test_with_heater.py
  idaes/models/properties/helmholtz/helmholtz.py
  idaes/models/properties/iapws95.py
  idaes/models/properties/swco2.py
  idaes/models/properties/tests/iapws95_plots.py
  idaes/models/properties/tests/prop_iapws95_nist_webbook.txt
  idaes/models/properties/tests/prop_swco2_nist_webbook.txt
  idaes/models/properties/tests/sat_prop_iapws95_nist_webbook.txt
  idaes/models/properties/tests/sat_prop_swco2_nist_webbook.txt
  idaes/models/properties/tests/test_iapws95.py
  idaes/models/properties/tests/test_iapws95_basic.py
  idaes/models/properties/tests/test_iapws95_integration.py
  idaes/models/properties/tests/test_swco2_basic.py
  idaes/models/properties/tests/test_swco2_integration.py
  idaes/models/properties/tests/test_swco2_transport.py
  idaes/models/unit_models/tests/test_feed.py
  idaes/models/unit_models/tests/test_feed_flash.py
  idaes/models/unit_models/tests/test_flash.py
  idaes/models/unit_models/tests/test_heat_exchanger.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_mixer.py
  idaes/models/unit_models/tests/test_product.py
  idaes/models/unit_models/tests/test_separator.py
  idaes/models/unit_models/tests/test_shell_and_tube_1D.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/subcritical_boiler_flowsheet.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/subcritical_boiler_init.json.gz
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/tests/subcritical_boiler_init.json.gz
  idaes/models_extra/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/models_extra/power_generation/unit_models/helm/valve_steam.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_interconnect.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_thin.py
  idaes/models_extra/power_generation/unit_models/tests/test_downcomer.py
  idaes/models_extra/power_generation/unit_models/tests/test_drum.py
  idaes/models_extra/power_generation/unit_models/tests/test_drum1D.py
  idaes/models_extra/power_generation/unit_models/tests/test_steamheater.py
  idaes/models_extra/power_generation/unit_models/tests/test_waterpipe.py
  idaes/models_extra/power_generation/unit_models/tests/test_watertank.py
Labels: Priority:High

#1010 Fix missing property mole_frac_comp for NGCC example
  idaes/models/properties/general_helmholtz/helmholtz_state.py
  idaes/models/properties/general_helmholtz/tests/test_with_heater.py
Labels: Priority:High

#1002 Fixing grid integration double-loop issue with initial status
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/util.py
Labels: Priority:High

#1011 Fix supercritical pfd output
  idaes/models_extra/power_generation/flowsheets/supercritical_power_plant/boiler_subflowsheet_build.py
  idaes/models_extra/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
  idaes/models_extra/power_generation/flowsheets/test/test_scsc.py
Labels: Priority:High

#1015 Add dens_star_mol to Helmholtz Property Block
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
  idaes/models/properties/general_helmholtz/helmholtz_state.py
Labels: Priority:High

#1018 Fix supercritical_steam_cycle PFD output
  idaes/models_extra/power_generation/flowsheets/supercritical_steam_cycle/supercritical_steam_cycle.py
Labels: Priority:High

#1007 Set and get scaling factor
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/common.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/porous_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_cell.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_module_simple.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/testing.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_triple_phase_boundary.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/triple_phase_boundary.py
Labels: Priority:Normal

#1005 Add PySMO's confidence interval function to new surrogate interface
  docs/explanations/modeling_extensions/surrogate/api/pysmo/pysmo_polyregression.rst
  idaes/core/surrogate/pysmo_surrogate.py
  idaes/core/surrogate/tests/test_pysmo_surrogate.py
Labels: Priority:Normal

#1024 Updating Pyomo in preparation for the 6.4.3 release
  setup.py
Labels: Priority:High

#1025 Minor Power Plant Costing Change to Allow Expressions
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
  idaes/models_extra/power_generation/costing/tests/test_power_plant_capcost.py
Labels: Priority:High

#1029 Updating the pyomo tag to the 6.4.3 release
  setup.py
Labels: Priority:High

#973 Get rid of default in documentation
  idaes/core/base/process_block.py
Labels: Priority:Normal

#1035 Pressure_changer doc update
  docs/reference_guides/model_libraries/generic/unit_models/pressure_changer.rst
Labels: documentation, Priority:Normal
