Repository IDAES/idaes-pse, pull requests merged in 2022-02, with the labels that each got.

#639 Links connect to unit models horizontally with a gap
  idaes/tests/test_version.py
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/js/cell_config.js
  idaes/ui/icons.py
  idaes/ui/mappings/mappings.json
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
  idaes/ui/tests/test_icons.py
Labels: Priority:Normal

#686 Remove deprecated copy_port_values
  idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py
  idaes/power_generation/unit_models/helm/turbine_multistage.py
Labels: Priority:High

#687 Add missing unit of measure
  idaes/power_generation/unit_models/helm/turbine_multistage.py
Labels: Priority:High

#678 Adding funding acknowledgement to README.md
  README.md
Labels: Priority:Normal

#690 Update property test harness to work with ``phase_component_set``
  idaes/generic_models/properties/tests/test_harness.py
Labels: Priority:Normal, core

#693 Insert value() method to resolve Boolean assertion error
  idaes/dmf/tests/test_util.py
  idaes/generic_models/properties/core/eos/tests/test_ceos_PR.py
Labels: bug, Priority:High, testing

#679 Updating CV1D reaction variables to use reaction package units
  idaes/core/control_volume0d.py
  idaes/core/control_volume1d.py
  idaes/core/tests/test_control_volume_0d.py
  idaes/core/tests/test_control_volume_1d.py
Labels: Priority:High

#655 Stream table brushing
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/fsvis/static/js/paper.js
  idaes/ui/fsvis/static/js/stream_table.js
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
Labels: Priority:Normal

#708 Fixing string checking of Expressions
  idaes/generic_models/properties/core/eos/tests/test_ideal.py
  idaes/generic_models/properties/core/reactions/tests/test_equilibrium_constant.py
Labels: bug, Priority:High, testing

#666 Utilities for dynamic optimization
  idaes/apps/nmpc/__init__.py
  idaes/apps/nmpc/cost_expressions.py
  idaes/apps/nmpc/dynamic_data/__init__.py
  idaes/apps/nmpc/dynamic_data/interval_data.py
  idaes/apps/nmpc/dynamic_data/tests/__init__.py
  idaes/apps/nmpc/dynamic_data/tests/test_interval_data.py
  idaes/apps/nmpc/tests/__init__.py
  idaes/apps/nmpc/tests/test_cost_expressions.py
Labels: Priority:Normal

#698 Fixes refresh button that used to ruin the link connections
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/mappings/mappings.json
  idaes/ui/tests/test_icons.py
Labels: Priority:High

#702 Cleaning unit model mappings
  idaes/ui/fsvis/static/images/icons/default.svg
  idaes/ui/icons.py
  idaes/ui/mappings/mappings.json
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
  idaes/ui/tests/test_icons.py
Labels: Priority:High

#710 Fixing issue with ALAMO trace files and validation data
  idaes/surrogate/alamopy.py
  idaes/surrogate/tests/alamotrace_w_validation.trc
  idaes/surrogate/tests/test_alamopy.py
Labels: bug, user request, Priority:High, surrogates

#699 Adding a toggle to hide the stream names and show them
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/toolbar.js
  idaes/ui/fsvis/templates/index.html
Labels: Priority:Normal

#700 Adding a toggle feature to turn off the stream brushing
  idaes/ui/fsvis/static/css/bootstrap/bootstrap.css
  idaes/ui/fsvis/static/css/main.css
  idaes/ui/fsvis/static/js/paper.js
  idaes/ui/fsvis/static/js/stream_table.js
  idaes/ui/fsvis/templates/index.html
Labels: Priority:Normal, flowsheet viewer

#722 Bump the Pyomo tag to the Pyomo 6.3 release
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
  idaes/apps/uncertainty_propagation/uncertainties.py
  setup.py
Labels: Priority:High

#555 FTPx initialization
  idaes/core/control_volume0d.py
  idaes/core/util/exceptions.py
  idaes/core/util/tests/test_exceptions.py
  idaes/generic_models/properties/core/eos/ideal.py
  idaes/generic_models/properties/core/examples/tests/test_BT_PR.py
  idaes/generic_models/properties/core/phase_equil/henry.py
  idaes/generic_models/properties/core/phase_equil/tests/test_henry.py
  idaes/generic_models/properties/core/state_definitions/FTPx.py
  idaes/generic_models/properties/core/state_definitions/tests/test_FTPx.py
Labels: Priority:High

#720 Require Click version 8 or greater
  setup.py
Labels: Priority:High

#726 Add Python 3.10 to CI checks
  .github/actions/setup-idaes/action.yml
  .github/workflows/core.yml
  .github/workflows/integration.yml
  README.md
  idaes/core/util/tags.py
  idaes/surrogate/pysmo/tests/test_polynomial_regression.py
Labels: Priority:High

#685 Power plant costing update
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/costing/tests/test_NGCC_costing.py
  idaes/power_generation/costing/tests/test_power_plant_costing.py
Labels: Priority:High
