Repository IDAES/idaes-pse, pull requests merged in 2022-07, with the labels that each got.

#899 Include agc Pmin and Pmax in double loop model data
  idaes/apps/grid_integration/model_data.py
Labels: bug, Priority:High

#874 Fix ajax response when a PUT /fs request is called to save a model
  idaes/core/ui/flowsheet.py
  idaes/core/ui/fsvis/model_server.py
  idaes/core/ui/fsvis/static/js/main.js
  idaes/core/ui/fsvis/static/js/stream_table.js
  idaes/core/ui/fsvis/static/js/toolbar.js
  idaes/core/ui/fsvis/tests/test_model_server.py
Labels: Priority:High

#900 Fix test and integration badge links
  README.md
Labels: Priority:Low

#884 Surrogate Visualization Tests and Documentation
  docs/explanations/modeling_extensions/surrogate/index.rst
  docs/explanations/modeling_extensions/surrogate/plotting/index.rst
  docs/explanations/modeling_extensions/surrogate/plotting/surrparity.png
  docs/images/surrparity.png
  idaes/core/surrogate/plotting/tests/alamo_surrogate.json
  idaes/core/surrogate/plotting/tests/keras_surrogate/idaes_info.json
  idaes/core/surrogate/plotting/tests/keras_surrogate/keras_metadata.pb
  idaes/core/surrogate/plotting/tests/keras_surrogate/saved_model.pb
  idaes/core/surrogate/plotting/tests/keras_surrogate/variables/variables.data-00000-of-00001
  idaes/core/surrogate/plotting/tests/keras_surrogate/variables/variables.index
  idaes/core/surrogate/plotting/tests/pysmo_krig_surrogate.json
  idaes/core/surrogate/plotting/tests/pysmo_poly_surrogate.json
  idaes/core/surrogate/plotting/tests/pysmo_rbf_surrogate.json
  idaes/core/surrogate/plotting/tests/reformer-data.csv
  idaes/core/surrogate/plotting/tests/test_alamo_plotting.py
  idaes/core/surrogate/plotting/tests/test_keras_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_krig_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_poly_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_rbf_plotting.py
  setup.py
Labels: Priority:Normal

#871 MEA CCS costing
  idaes/models_extra/power_generation/costing/power_plant_costing.py
  idaes/models_extra/power_generation/costing/tests/test_CCS_costing.py
Labels: Priority:Normal

#911 Add configuration and requirement for pre-commit framework for Git hooks
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: Priority:High

#876 Adding build_port method to StateBlocks
  idaes/core/base/property_base.py
  idaes/core/base/tests/test_property_base.py
  idaes/core/base/tests/test_unit_model.py
  idaes/core/base/unit_model.py
Labels: enhancement, Priority:Normal, core

#916 Fixing bug in Separator report method
  idaes/core/ui/tests/serialized_boiler_flowsheet.json
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/tests/test_separator.py
Labels: bug, Priority:Normal, unit models

#905 SSLW Compressor Exceptions
  idaes/models/costing/SSLW.py
  idaes/models/costing/tests/test_SSLW_costing.py
Labels: Priority:High

#923 Update Pyomo tag
  setup.py
Labels: Priority:High
