Repository IDAES/idaes-pse, pull requests merged in 2022-04, with the labels that each got.

#777 Re-enable "Build Sphinx docs" CI check
  .github/workflows/core.yml
  docs/build.py
  docs/reference_guides/core/process_block.rst
  idaes/apps/matopt/materials/canvas.py
  idaes/apps/matopt/materials/design.py
  idaes/apps/matopt/opt/mat_modeling.py
  idaes/apps/matopt/opt/pyomo_modeling.py
  idaes/apps/nmpc/dynamic_data/interval_data.py
  idaes/core/base/unit_model.py
  idaes/dmf/resource.py
  idaes/generic_models/costing/SSLW.py
  idaes/generic_models/costing/costing_base.py
  idaes/models_extra/power_generation/costing/costing_dictionaries.py
  idaes/models_extra/power_generation/costing/power_plant_costing.py
  idaes/models_extra/power_generation/flowsheets/supercritical_power_plant/boiler_subflowsheet_build.py
Labels: Priority:High

#758 Fix the icon rotation gap problem
  idaes/ui/fsvis/static/js/cell_config.js
  idaes/ui/fsvis/static/js/paper.js
Labels: Priority:Normal

#786 Fixing test failure due to new pint release
  idaes/core/util/tests/test_tags.py
Labels: bug, Priority:High, testing, dependencies

#785 MEA solvent viscosity calculation correction
  idaes/models_extra/column_models/properties/MEA_solvent.py
  idaes/models_extra/column_models/properties/tests/test_mea_solvent.py
Labels: bug, Priority:Normal, property packages

#652 Add optional requirement and simple test case for Prescient
  idaes/tests/prescient/5bus/DAY_AHEAD_load.csv
  idaes/tests/prescient/5bus/DAY_AHEAD_renewables.csv
  idaes/tests/prescient/5bus/REAL_TIME_load.csv
  idaes/tests/prescient/5bus/REAL_TIME_renewables.csv
  idaes/tests/prescient/5bus/__init__.py
  idaes/tests/prescient/5bus/branch.csv
  idaes/tests/prescient/5bus/bus.csv
  idaes/tests/prescient/5bus/gen.csv
  idaes/tests/prescient/5bus/initial_status.csv
  idaes/tests/prescient/5bus/reserves.csv
  idaes/tests/prescient/5bus/simulation_objects.csv
  idaes/tests/prescient/5bus/timeseries_pointers.csv
  idaes/tests/prescient/__init__.py
  idaes/tests/prescient/test_prescient.py
  setup.py
Labels: Priority:Normal

#780 Add enthalpy mixing constraint to pipeline node models
  idaes/models_extra/gas_distribution/properties/natural_gas.py
  idaes/models_extra/gas_distribution/properties/tests/test_natural_gas.py
  idaes/models_extra/gas_distribution/unit_models/node.py
  idaes/models_extra/gas_distribution/unit_models/tests/test_flowsheet.py
  idaes/models_extra/gas_distribution/unit_models/tests/test_node.py
Labels: enhancement, Priority:Normal

#792 Fix typo in pipeline natural gas property package
  idaes/models_extra/gas_distribution/properties/natural_gas.py
  idaes/models_extra/gas_distribution/properties/tests/test_natural_gas.py
Labels: Priority:High

#788 Add machine name to binary packages.
  docs/tutorials/getting_started/binaries.rst
  docs/tutorials/getting_started/index.rst
  idaes/commands/extensions.py
  idaes/commands/tests/test_commands.py
  idaes/commands/util/__init__.py
  idaes/commands/util/download_bin.py
  idaes/commands/util/tests/__init__.py
  idaes/commands/util/tests/test_download_bin.py
  idaes/config.py
  idaes/tests/test_config.py
  setup.py
Labels: Priority:High

#800 Improving some properties tests
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_gas_prop.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_rxn_prop.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_solid_prop.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_gas_prop.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_rxn_prop.py
  idaes/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/tests/test_CLC_solid_prop.py
  idaes/models/properties/activity_coeff_models/tests/test_ideal_ideal_FTPz.py
  idaes/models/properties/activity_coeff_models/tests/test_ideal_ideal_FcTP.py
  idaes/models/properties/cubic_eos/tests/test_BT_example.py
Labels: bug, Priority:Normal, property packages, testing

#756 Bubbling Fluidized Bed Updates Scaling and Units
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/bubbling_fluidized_bed.rst
  idaes/gas_solid_contactors/flowsheets/ss_BFB_methane_combustion.py
  idaes/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/gas_solid_contactors/unit_models/tests/test_BFB.py
Labels: Priority:Normal

#771 Add PySMO support for (new) SurrogateTrainer API
  idaes/surrogate/pysmo_surrogate.py
  idaes/surrogate/tests/test_pysmo_surrogate.py
Labels: Priority:High

#787 Grid integration double loop part 1
  idaes/apps/grid_integration/__init__.py
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/examples/__init__.py
  idaes/apps/grid_integration/examples/gen.csv
  idaes/apps/grid_integration/examples/lmp_forecasts_concat.csv
  idaes/apps/grid_integration/examples/lmp_forecasts_example.csv
  idaes/apps/grid_integration/examples/thermal_generator.py
  idaes/apps/grid_integration/examples/thermal_generator_prescient_plugin.py
  idaes/apps/grid_integration/forecaster.py
  idaes/apps/grid_integration/multiperiod/__init__.py
  idaes/apps/grid_integration/multiperiod/multiperiod.py
  idaes/apps/grid_integration/tests/__init__.py
  idaes/apps/grid_integration/tests/bidder_integration_test_plugin.py
  idaes/apps/grid_integration/tests/self_scheduler_integration_test_plugin.py
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/apps/grid_integration/tests/test_tracker.py
  idaes/apps/grid_integration/tests/util.py
  idaes/apps/grid_integration/tracker.py
  idaes/tests/prescient/test_prescient.py
Labels: Priority:High

#742 Adding Feeds & Products to the stream table
  idaes/ui/flowsheet.py
  idaes/ui/fsvis/static/js/main.js
  idaes/ui/fsvis/tests/test_fsvis.py
  idaes/ui/tests/demo_flowsheet.json
  idaes/ui/tests/flash_flowsheet.json
  idaes/ui/tests/serialized_boiler_flowsheet.json
  idaes/ui/tests/test_flowsheet.py
Labels: Priority:High

#783 Display the views before refreshing
  idaes/ui/fsvis/static/js/main.js
Labels: Priority:Normal

#805 Column model and MEA property corrections
  idaes/models_extra/column_models/solvent_column.py
Labels: bug, Priority:Normal, property packages

#815 Fixing skipping tests for prescient
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/examples/thermal_generator.py
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/tests/prescient/test_prescient.py
Labels: bug, Priority:High, testing, dependencies

#806 PETSc trajectory concatination
  docs/reference_guides/core/solvers.rst
  idaes/commands/wrap_solver_wsl.py
  idaes/config.py
  idaes/core/solvers/features.py
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
  idaes/core/solvers/tests/test_petsc_pid.py
Labels: enhancement, Priority:Normal

#799 Dh and scaling
  docs/reference_guides/core/util/scaling.rst
  idaes/core/util/model_diagnostics.py
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_scaling.py
Labels: enhancement, Priority:Normal

#820 Fixing incorrect doc strings in control volume methods
  idaes/core/base/control_volume0d.py
  idaes/core/base/control_volume1d.py
Labels: bug, documentation, Priority:Normal, core

#827 Fix serializing with top level BlockData
  idaes/core/util/model_serializer.py
  idaes/core/util/tests/test_model_serializer.py
Labels: bug, Priority:High, core

#828 Pysmo expression generator fix for scalar pyomo variables
  idaes/core/surrogate/pysmo/kriging.py
  idaes/core/surrogate/pysmo/polynomial_regression.py
  idaes/core/surrogate/pysmo/radial_basis_function.py
Labels: Priority:Normal

#829 Re-adding PHE model
  docs/reference_guides/model_libraries/index.rst
  docs/reference_guides/model_libraries/models_extra/index.rst
  docs/reference_guides/model_libraries/models_extra/phe.rst
  docs/reference_guides/model_libraries/models_extra/phe_a.png
  docs/reference_guides/model_libraries/models_extra/phe_b.png
  idaes/models_extra/column_models/plate_heat_exchanger.py
  idaes/models_extra/column_models/tests/test_plate_heat_exchanger.py
Labels: Priority:Normal, unit models
