Repository IDAES/idaes-pse, pull requests merged in 2022-03, with the labels that each got.

#739 Update omlt version
  setup.py
Labels: Priority:High

#734 Update solvent_reboiler.py
  idaes/generic_models/unit_models/column_models/solvent_reboiler.py
Labels: bug, Priority:Normal, unit models

#724 IDAES v2.0: Initialization changes
  idaes/core/unit_model.py
  idaes/generic_models/unit_models/feed.py
  idaes/generic_models/unit_models/heat_exchanger.py
  idaes/generic_models/unit_models/heat_exchanger_1D.py
  idaes/generic_models/unit_models/heat_exchanger_ntu.py
  idaes/generic_models/unit_models/mixer.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/generic_models/unit_models/product.py
  idaes/generic_models/unit_models/separator.py
  idaes/generic_models/unit_models/skeleton_model.py
  idaes/generic_models/unit_models/statejunction.py
  idaes/generic_models/unit_models/translator.py
  idaes/generic_models/unit_models/valve.py
  idaes/power_generation/unit_models/tests/test_boiler_heat_exchanger.py
Labels: enhancement, Priority:High, core, unit models, IDAES v2.0

#738 Ensure that pytest is the only strict requirement for running test suite for all installation modes
  .github/workflows/integration.yml
  docs/tutorials/getting_started/index.rst
  idaes/generic_models/properties/core/coolprop/tests/test_coolprop_wrapper.py
  idaes/generic_models/properties/core/eos/tests/test_enrtl.py
  idaes/surrogate/keras_surrogate.py
  idaes/surrogate/tests/test_keras_surrogate.py
  idaes/tests/test_headers.py
  setup.py
Labels: Priority:High

#715 Add SOEC design point model
  docs/reference_guides/model_libraries/power_generation/unit_models/index.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/soec_design.rst
  idaes/generic_models/unit_models/mixer.py
  idaes/power_generation/unit_models/boiler_heat_exchanger.py
  idaes/power_generation/unit_models/helm/splitter.py
  idaes/power_generation/unit_models/helm/valve_steam.py
  idaes/power_generation/unit_models/soec_design.py
  idaes/power_generation/unit_models/tests/test_soec_design.py
Labels: Priority:High

#743 Fix power generation initialize -> initialize_build
  idaes/power_generation/unit_models/boiler_fireside.py
  idaes/power_generation/unit_models/boiler_heat_exchanger.py
  idaes/power_generation/unit_models/boiler_heat_exchanger_2D.py
  idaes/power_generation/unit_models/downcomer.py
  idaes/power_generation/unit_models/drum.py
  idaes/power_generation/unit_models/drum1D.py
  idaes/power_generation/unit_models/feedwater_heater_0D.py
  idaes/power_generation/unit_models/feedwater_heater_0D_dynamic.py
  idaes/power_generation/unit_models/heat_exchanger_3streams.py
  idaes/power_generation/unit_models/helm/compressor.py
  idaes/power_generation/unit_models/helm/condenser_ntu.py
  idaes/power_generation/unit_models/helm/mixer.py
  idaes/power_generation/unit_models/helm/phase_separator.py
  idaes/power_generation/unit_models/helm/pump.py
  idaes/power_generation/unit_models/helm/splitter.py
  idaes/power_generation/unit_models/helm/turbine.py
  idaes/power_generation/unit_models/helm/turbine_inlet.py
  idaes/power_generation/unit_models/helm/turbine_multistage.py
  idaes/power_generation/unit_models/helm/turbine_outlet.py
  idaes/power_generation/unit_models/helm/turbine_stage.py
  idaes/power_generation/unit_models/helm/valve_steam.py
  idaes/power_generation/unit_models/steamheater.py
  idaes/power_generation/unit_models/tests/test_boiler_heat_exchanger.py
  idaes/power_generation/unit_models/waterpipe.py
  idaes/power_generation/unit_models/watertank.py
  idaes/power_generation/unit_models/waterwall_section.py
Labels: Priority:Normal, IDAES v2.0

#744 Fix redundant deprecation in warning
  idaes/core/util/tags.py
Labels: Priority:Normal

#741 New IDAES costing framework
  idaes/core/flowsheet_model.py
  idaes/core/unit_model.py
  idaes/core/util/exceptions.py
  idaes/core/util/misc.py
  idaes/core/util/tests/test_exceptions.py
  idaes/core/util/tests/test_misc.py
  idaes/generic_models/costing/SSLW.py
  idaes/generic_models/costing/__init__.py
  idaes/generic_models/costing/costing_base.py
  idaes/generic_models/costing/tests/__init__.py
  idaes/generic_models/costing/tests/test_SSLW_costing.py
  idaes/generic_models/costing/tests/test_costing_base.py
  idaes/generic_models/unit_models/cstr.py
  idaes/generic_models/unit_models/flash.py
  idaes/generic_models/unit_models/heat_exchanger.py
  idaes/generic_models/unit_models/heat_exchanger_ntu.py
  idaes/generic_models/unit_models/plug_flow_reactor.py
  idaes/generic_models/unit_models/pressure_changer.py
  idaes/generic_models/unit_models/stoichiometric_reactor.py
  idaes/power_generation/carbon_capture/mea_solvent_system/unit_models/plate_heat_exchanger.py
  idaes/power_generation/costing/power_plant_costing.py
  idaes/power_generation/costing/tests/test_power_plant_costing.py
  idaes/power_generation/unit_models/helm/condenser_ntu.py
Labels: enhancement, user request, Priority:High, core, IDAES v2.0

#755 Update Pyomo tag to the 6.4.0 release
  setup.py
Labels: Priority:High

#750 PySMO: Fix pandas deprecation warnings
  idaes/surrogate/pysmo/polynomial_regression.py
Labels: Priority:Normal, surrogates

#714 Add wall temperature and heat accumulation terms to the 0D heat exchanger
  docs/reference_guides/model_libraries/generic/unit_models/heat_exchanger_lc.rst
  docs/reference_guides/model_libraries/generic/unit_models/index.rst
  idaes/generic_models/unit_models/__init__.py
  idaes/generic_models/unit_models/heat_exchanger_lc.py
  idaes/generic_models/unit_models/tests/test_heat_exchanger_lc.py
Labels: user request, Priority:Normal, unit models

#667 Unit models and property package for natural gas pipelines
  idaes/gas_distribution/__init__.py
  idaes/gas_distribution/properties/__init__.py
  idaes/gas_distribution/properties/natural_gas.py
  idaes/gas_distribution/properties/tests/__init__.py
  idaes/gas_distribution/properties/tests/test_natural_gas.py
  idaes/gas_distribution/unit_models/__init__.py
  idaes/gas_distribution/unit_models/compressor.py
  idaes/gas_distribution/unit_models/node.py
  idaes/gas_distribution/unit_models/pipeline.py
  idaes/gas_distribution/unit_models/tests/__init__.py
  idaes/gas_distribution/unit_models/tests/test_compressor.py
  idaes/gas_distribution/unit_models/tests/test_flowsheet.py
  idaes/gas_distribution/unit_models/tests/test_node.py
  idaes/gas_distribution/unit_models/tests/test_pipeline.py
  idaes/gas_distribution/unit_models/tests/test_pipeline_compressor.py
Labels: Priority:Normal

#772 Fix bugs in modular properties initialization
  idaes/generic_models/properties/core/eos/tests/test_ceos_CO2_H2O.py
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/power_generation/properties/natural_gas_PR.py
Labels: bug, Priority:Normal, property packages

#774 Add utility to calculate time derivative vars.
  docs/reference_guides/core/solvers.rst
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
  idaes/core/solvers/tests/test_petsc_pid.py
Labels: enhancement
