Repository IDAES/idaes-pse, pull requests merged in 2022-08, with the labels that each got.

#925 Create work term for Pressure Changer with EnergyBalanceType.none
  idaes/models/unit_models/pressure_changer.py
  idaes/models/unit_models/tests/test_pressure_changer.py
Labels: bug, Priority:High

#922 Switch ProcessBlock 'default' argument to just use keyword arguments
  docs/explanations/components/property_package/general_reactions/generic_reactions.rst
  docs/how_to_guides/workflow/general.rst
  docs/reference_guides/core/process_block.rst
  docs/reference_guides/core/util/unit_costing.rst
  docs/reference_guides/model_libraries/generic/control/pid.rst
  docs/reference_guides/model_libraries/generic/property_models/iapws95.rst
  docs/reference_guides/model_libraries/generic/property_models/interrogator.rst
  docs/reference_guides/model_libraries/generic/property_models/swco2.rst
  docs/reference_guides/model_libraries/generic/unit_models/compressor.rst
  docs/reference_guides/model_libraries/generic/unit_models/heat_exchanger.rst
  docs/reference_guides/model_libraries/generic/unit_models/heat_exchanger_lc.rst
  docs/reference_guides/model_libraries/generic/unit_models/heater.rst
  docs/reference_guides/model_libraries/generic/unit_models/pressure_changer.rst
  docs/reference_guides/model_libraries/generic/unit_models/pump.rst
  docs/reference_guides/model_libraries/generic/unit_models/turbine.rst
  docs/reference_guides/model_libraries/generic/unit_models/valve.rst
  docs/reference_guides/model_libraries/power_generation/costing/power_plant_costing.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/boiler_heat_exchanger.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/feedwater_heater_0D.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/soec_design.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/steam_valve.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/turbine_inlet.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/turbine_multistage.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/turbine_outlet.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/turbine_stage.rst
  idaes/apps/caprese/examples/cstr_model.py
  idaes/apps/uncertainty_propagation/examples/NRTL_model_scripts.py
  idaes/core/base/process_block.py
  idaes/core/base/property_base.py
  idaes/core/base/reaction_base.py
  idaes/core/base/tests/test_components.py
  idaes/core/base/tests/test_control_volume_0d.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/base/tests/test_flowsheet_model.py
  idaes/core/solvers/homotopy.py
  idaes/models/properties/helmholtz/helmholtz.py
  idaes/models/properties/iapws95.py
  idaes/models/properties/modular_properties/base/generic_property.py
  idaes/models/properties/swco2.py
  idaes/models/unit_models/cstr.py
  idaes/models/unit_models/heater.py
  idaes/models/unit_models/pressure_changer.py
  idaes/models/unit_models/stoichiometric_reactor.py
  idaes/models_extra/power_generation/control/tests/test_pid_pump.py
  idaes/models_extra/power_generation/unit_models/balance.py
  idaes/models_extra/power_generation/unit_models/feedwater_heater_0D.py
  idaes/models_extra/power_generation/unit_models/soec_design.py
  idaes/models_extra/power_generation/unit_models/tests/test_boiler_heat_exchanger.py
  setup.py
Labels: Priority:High

#933 Fix multistage turbine test
  idaes/models_extra/power_generation/unit_models/helm/tests/test_turbine_multistage.py
  idaes/models_extra/power_generation/unit_models/helm/turbine_multistage.py
Labels: Priority:High

#885 Docs Getting Started Reorg
  docs/_templates/page.html
  docs/how_to_guides/index.rst
  docs/how_to_guides/versioned_idaes_install.rst
  docs/index.rst
  docs/static/css/custom.css
  docs/tutorials/advanced_install/index.rst
  docs/tutorials/getting_started/index.rst
  docs/tutorials/getting_started/install_templates/conda_idaes_pse.md
  docs/tutorials/getting_started/install_templates/examples.md
  docs/tutorials/getting_started/install_templates/extensions.md
  docs/tutorials/getting_started/install_templates/quickstart.md
  docs/tutorials/getting_started/install_templates/run_tests.md
  docs/tutorials/getting_started/linux.rst
  docs/tutorials/getting_started/mac_osx.rst
  docs/tutorials/getting_started/windows.rst
Labels: documentation, Priority:Normal

#932 Restore documentation search in Sphinx/ReadTheDocs
  docs/static/doctools.js
  docs/static/documentation_options.js
  docs/static/jquery-3.2.1.js
  docs/static/jquery.js
  docs/static/js/modernizr.min.js
  docs/static/js/theme.js
  docs/static/language_data.js
  docs/static/pygments.css
  docs/static/searchtools.js
  docs/static/underscore-1.3.1.js
  docs/static/underscore.js
  docs/static/websupport.js
Labels: Priority:High

#901 Export as PNG & jpeg
  idaes/core/ui/fsvis/static/js/toolbar.js
  idaes/core/ui/fsvis/templates/index.html
Labels: Priority:Normal

#908 Add additional methods to `MultiPeriodModel` class
  idaes/apps/grid_integration/__init__.py
  idaes/apps/grid_integration/multiperiod/multiperiod.py
  idaes/apps/grid_integration/multiperiod/tests/__init__.py
  idaes/apps/grid_integration/multiperiod/tests/test_multiperiod.py
Labels: Priority:High

#936 Bump bin version to 3.0.0
  idaes/config.py
Labels: Priority:High

#855 Real-time bidding in double loop
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/examples/gen.csv
  idaes/apps/grid_integration/examples/lmp_forecasts_concat.csv
  idaes/apps/grid_integration/examples/lmp_forecasts_example.csv
  idaes/apps/grid_integration/examples/thermal_generator.py
  idaes/apps/grid_integration/examples/thermal_generator_prescient_plugin.py
  idaes/apps/grid_integration/examples/utils.py
  idaes/apps/grid_integration/forecaster.py
  idaes/apps/grid_integration/model_data.py
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_model_data.py
  idaes/apps/grid_integration/tests/test_tracker.py
  idaes/apps/grid_integration/tests/util.py
  idaes/apps/grid_integration/tracker.py
Labels: Priority:High

#915 Fixing Modifying graph elements in the flowsheet
  idaes/core/ui/flowsheet.py
Labels: Priority:High

#872 Models needed for sofc example
  idaes/models_extra/power_generation/properties/natural_gas_PR.py
  idaes/models_extra/power_generation/properties/sofc/sofc_keras_surrogate.py
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/idaes_info.json
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/saved_model.pb
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/variables/variables.data-00000-of-00001
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/variables/variables.index
  idaes/models_extra/power_generation/properties/tests/test_sofc_surrogates.py
  idaes/models_extra/power_generation/unit_models/cpu.py
  idaes/models_extra/power_generation/unit_models/tests/test_cpu.py
Labels: Priority:High

#931 Adding multi select box for the ui
  idaes/core/ui/fsvis/static/js/paper.js
Labels: Priority:Normal

#928 Process Costing Framework Documentation
  docs/reference_guides/core/costing/costing_framework.rst
  docs/reference_guides/core/costing/costing_libraries.rst
  docs/reference_guides/core/costing/index.rst
  docs/reference_guides/core/index.rst
  docs/reference_guides/model_libraries/generic/costing/index.rst
  docs/reference_guides/model_libraries/generic/costing/process_costing_sslw.rst
  docs/reference_guides/model_libraries/generic/index.rst
  idaes/models/costing/SSLW.py
Labels: Priority:High

#914 Correction to the MEA solvent property package and column
  idaes/models/unit_models/tests/test_hx_ntu.py
  idaes/models_extra/column_models/MEAsolvent_column.py
  idaes/models_extra/column_models/properties/MEA_solvent.py
  idaes/models_extra/column_models/properties/tests/test_mea_solvent.py
  idaes/models_extra/column_models/solvent_column.py
  idaes/models_extra/column_models/tests/test_MEAsolvent_column.py
  idaes/models_extra/column_models/tests/test_plate_heat_exchanger.py
  idaes/models_extra/column_models/tests/test_solvent_column.py
  idaes/models_extra/column_models/tests/test_solvent_condenser.py
  idaes/models_extra/column_models/tests/test_solvent_reboiler.py
Labels: Priority:Normal

#938 Only aggregating flows with at least one registered flow
  idaes/core/base/costing_base.py
  idaes/core/base/tests/test_costing_base.py
Labels: Priority:Normal
