Repository IDAES/idaes-pse, pull requests merged in 2022-01, with the labels that each got.

#647 Fixing bug in generic properties initialization
  idaes/generic_models/properties/core/generic/generic_property.py
  idaes/surrogate/pysmo/tests/test_utils.py
Labels: bug, Priority:High, property packages

#552 Petsc DAE Solver Utils
  .github/actions/setup-idaes/action.yml
  docs/getting_started/binaries.rst
  docs/technical_specs/core/solvers.rst
  idaes/config.py
  idaes/core/solvers/features.py
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
  idaes/core/solvers/tests/test_petsc_pid.py
  idaes/core/solvers/tests/test_solvers.py
  idaes/util/download_bin.py
Labels: Priority:Normal, approved

#608 Restyle & reorganize main index page
  docs/index.rst
  docs/static/css/custom.css
Labels: Priority:Normal

#634 FB0D and methane iron OC properties updates
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/gas_phase_thermo.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/hetero_reactions.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/solid_phase_thermo.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_gas_prop.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_rxn_prop.py
  idaes/gas_solid_contactors/properties/methane_iron_OC_reduction/tests/test_CLC_solid_prop.py
  idaes/gas_solid_contactors/unit_models/fixed_bed_0D.py
  idaes/gas_solid_contactors/unit_models/tests/test_FB0D.py
Labels: Priority:Normal, property packages, unit models

#670 Adding units for Keq in MEA solvent properties
  idaes/power_generation/carbon_capture/mea_solvent_system/properties/MEA_solvent.py
Labels: bug, Priority:High, property packages

#640 Adding normalizing scaler constructor
  idaes/surrogate/sampling/scaling.py
  idaes/surrogate/sampling/tests/test_scaling.py
Labels: enhancement, Priority:Normal

#656 Fix #654 where tests in test_fsvis.py don't open browser windows anymore
  idaes/ui/fsvis/tests/test_fsvis.py
Labels: Priority:Normal

#620 Generic property interface with CoolProp
  idaes/core/components.py
  idaes/core/util/misc.py
  idaes/generic_models/properties/core/coolprop/__init__.py
  idaes/generic_models/properties/core/coolprop/coolprop_forms.py
  idaes/generic_models/properties/core/coolprop/coolprop_wrapper.py
  idaes/generic_models/properties/core/coolprop/tests/__init__.py
  idaes/generic_models/properties/core/coolprop/tests/test_coolprop_forms.py
  idaes/generic_models/properties/core/coolprop/tests/test_coolprop_wrapper.py
  idaes/generic_models/properties/core/examples/BT_PR.py
  idaes/generic_models/properties/core/generic/generic_property.py
  setup.py
Labels: enhancement, Priority:Normal, property packages
