Repository IDAES/idaes-pse, pull requests merged in 2023-11, with the labels that each got.

#1283 Solid-Liquid Separator Base Model
  docs/reference_guides/model_libraries/generic/unit_models/index.rst
  docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/index.rst
  docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/sl_separator.rst
  docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/thickener0d.rst
  idaes/models/unit_models/flash.py
  idaes/models/unit_models/mscontactor.py
  idaes/models/unit_models/solid_liquid/__init__.py
  idaes/models/unit_models/solid_liquid/sl_separator.py
  idaes/models/unit_models/solid_liquid/tests/__init__.py
  idaes/models/unit_models/solid_liquid/tests/test_sl_separator.py
  idaes/models/unit_models/solid_liquid/tests/test_thickener.py
  idaes/models/unit_models/solid_liquid/thickener.py
  idaes/models/unit_models/tests/test_mscontactor.py
Labels: enhancement, Priority:Normal, unit models, WaterTAP, PrOMMiS

#1268 Diagnostic tool to look for potential evaluation errors
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: Priority:Normal

#1282 Add SCIP solver for testing
  .github/actions/setup-idaes/action.yml
  idaes/core/util/testing.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_scip_for_testing.py
  setup.py
Labels: Priority:High

#1289 Adding support for inherent reactions in Mixer and Separator
  idaes/models/unit_models/mixer.py
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/tests/test_mixer.py
  idaes/models/unit_models/tests/test_separator.py
Labels: bug, Priority:High, unit models, WaterTAP, PrOMMiS

#1293 Fixing errors due to bound checking in nl writer
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_utility_minimization.py
  idaes/models/properties/modular_properties/examples/tests/test_BT_PR.py
  idaes/models/unit_models/tests/test_equilibrium_reactor.py
  idaes/models/unit_models/tests/test_hx_ntu.py
Labels: bug, Priority:High, testing, backward-compat, pyomo
