Repository IDAES/idaes-pse, pull requests merged in 2023-03, with the labels that each got.

#1111 Adding more pylint checks
  .github/workflows/core.yml
  idaes/apps/grid_integration/forecaster.py
  idaes/apps/grid_integration/model_data.py
  idaes/apps/grid_integration/multiperiod/multiperiod.py
  idaes/apps/roundingRegression/RoundingRegression.py
  idaes/commands/base.py
  idaes/commands/examples.py
  idaes/core/base/costing_base.py
  idaes/core/base/property_meta.py
  idaes/core/dmf/codesearch.py
  idaes/core/dmf/getver.py
  idaes/core/dmf/help.py
  idaes/core/dmf/magics.py
  idaes/core/initialization/initializer_base.py
  idaes/core/solvers/petsc.py
  idaes/core/surrogate/alamopy.py
  idaes/core/surrogate/pysmo/polynomial_regression.py
  idaes/core/surrogate/pysmo/radial_basis_function.py
  idaes/core/surrogate/pysmo_surrogate.py
  idaes/core/surrogate/surrogate_block.py
  idaes/core/ui/flowsheet.py
  idaes/core/ui/fsvis/fsvis.py
  idaes/core/ui/icons/positioning.py
  idaes/core/util/initialization.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/model_serializer.py
  idaes/core/util/phase_equilibria.py
  idaes/core/util/scaling.py
  idaes/core/util/tags.py
  idaes/core/util/utility_minimization.py
  idaes/models/properties/helmholtz/helmholtz.py
  idaes/models_extra/column_models/MEAsolvent_column.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/steam_cycle_flowsheet.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
  idaes/models_extra/power_generation/unit_models/helm/valve_steam.py
  idaes/models_extra/power_generation/unit_models/soec_design.py
Labels: Priority:Normal, testing

#1107 Verify potentially unsafe tarfiles before extraction
  idaes/commands/util/download_bin.py
  idaes/commands/util/tests/test_download_bin.py
Labels: Priority:Normal

#1112 Even more pylint checks
  .github/workflows/core.yml
  .github/workflows/v1-compat.yml
  idaes/core/base/control_volume0d.py
  idaes/core/base/property_base.py
  idaes/core/base/reaction_base.py
  idaes/core/base/util.py
  idaes/core/dmf/datasets.py
  idaes/core/dmf/help.py
  idaes/core/dmf/model_data.py
  idaes/core/initialization/block_triangularization.py
  idaes/core/solvers/ipopt_l1.py
  idaes/core/solvers/petsc.py
  idaes/core/surrogate/alamopy.py
  idaes/core/surrogate/keras_surrogate.py
  idaes/core/surrogate/pysmo/radial_basis_function.py
  idaes/core/surrogate/pysmo/sampling.py
  idaes/core/surrogate/pysmo_surrogate.py
  idaes/core/surrogate/surrogate_block.py
  idaes/core/util/convergence/tests/conv_eval_classes.py
  idaes/core/util/misc.py
  idaes/core/util/scaling.py
  idaes/logger.py
  idaes/models/costing/SSLW.py
  idaes/models/properties/activity_coeff_models/BTX_activity_coeff_VLE.py
  idaes/models/properties/cubic_eos/cubic_prop_pack.py
  idaes/models/properties/iapws95.py
  idaes/models/properties/modular_properties/base/generic_reaction.py
  idaes/models/properties/modular_properties/base/utility.py
  idaes/models/properties/modular_properties/eos/ceos.py
  idaes/models/properties/modular_properties/eos/ceos_common.py
  idaes/models/properties/swco2.py
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/shell_and_tube_1d.py
  idaes/models/unit_models/skeleton_model.py
  idaes/models_extra/column_models/condenser.py
  idaes/models_extra/column_models/reboiler.py
  idaes/models_extra/column_models/tray.py
  idaes/models_extra/column_models/tray_column.py
  idaes/models_extra/column_models/util.py
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
  idaes/models_extra/power_generation/unit_models/boiler_fireside.py
  idaes/models_extra/power_generation/unit_models/boiler_heat_exchanger.py
  idaes/models_extra/power_generation/unit_models/cpu.py
  idaes/models_extra/power_generation/unit_models/helm/turbine_stage.py
Labels: Priority:Normal, testing

#1121 Removing HELMET from apps
  docs/archived_features/helmet.rst
  docs/archived_features/index.rst
  docs/explanations/modeling_extensions/index.rst
  docs/explanations/modeling_extensions/surrogate/helmet/index.rst
  docs/explanations/modeling_extensions/surrogate/index.rst
  docs/index.rst
  idaes/apps/helmet/AncillaryEquations.py
  idaes/apps/helmet/BasisFunctions.py
  idaes/apps/helmet/DataImport.py
  idaes/apps/helmet/DataManipulation.py
  idaes/apps/helmet/GAMSDataWrite.py
  idaes/apps/helmet/GAMSWrite.py
  idaes/apps/helmet/Helmet.py
  idaes/apps/helmet/Plotting.py
  idaes/apps/helmet/__init__.py
  idaes/apps/helmet/parseGAMS.py
  idaes/apps/helmet/tests/test_helmet_smoke.py
Labels: Priority:Normal, backward-compat, apps

#1120 Removing roundingRegression from apps
  idaes/apps/roundingRegression/RoundingRegression.py
  idaes/apps/roundingRegression/__init__.py
  idaes/apps/roundingRegression/test_roundingRegression.py
Labels: Priority:Normal, backward-compat, apps

#1123 Remove RIPE from repository
  docs/archived_features/helmet.rst
  docs/archived_features/index.rst
  docs/archived_features/ripe.rst
  docs/explanations/modeling_extensions/index.rst
  docs/explanations/modeling_extensions/surrogate/index.rst
  docs/explanations/modeling_extensions/surrogate/ripe/index.rst
  idaes/apps/ripe/__init__.py
  idaes/apps/ripe/atermconstruct.py
  idaes/apps/ripe/bounds.py
  idaes/apps/ripe/checkoptions.py
  idaes/apps/ripe/confinv.py
  idaes/apps/ripe/emsampling.py
  idaes/apps/ripe/genpyomo.py
  idaes/apps/ripe/kinforms.py
  idaes/apps/ripe/main.py
  idaes/apps/ripe/mechs.py
  idaes/apps/ripe/read.py
  idaes/apps/ripe/shared.py
  idaes/apps/ripe/targets.py
  idaes/apps/ripe/tests/test_ripesmoke.py
  idaes/apps/ripe/write.py
Labels: Priority:Normal, backward-compat, apps

#1124 Removing deprecated ALAMO interface
  docs/archived_features/ripe.rst
  idaes/apps/alamopy_depr/__init__.py
  idaes/apps/alamopy_depr/allcard.py
  idaes/apps/alamopy_depr/almconfidence.py
  idaes/apps/alamopy_depr/almerror.py
  idaes/apps/alamopy_depr/almpickle.py
  idaes/apps/alamopy_depr/almplot.py
  idaes/apps/alamopy_depr/almpywriter.py
  idaes/apps/alamopy_depr/almwriter.py
  idaes/apps/alamopy_depr/doalamo.py
  idaes/apps/alamopy_depr/examples.py
  idaes/apps/alamopy_depr/mapminmax.py
  idaes/apps/alamopy_depr/multos.py
  idaes/apps/alamopy_depr/remapminmax.py
  idaes/apps/alamopy_depr/shared.py
  idaes/apps/alamopy_depr/tests/examples.py
  idaes/apps/alamopy_depr/tests/test_alamosmoke.py
Labels: Priority:Normal, surrogates, backward-compat, apps

#1122 First pass at adding code owners
  .github/CODEOWNERS
Labels: Priority:Normal

#1128 Removing models_extra/carbon_capture folder
  idaes/models_extra/carbon_capture/__init__.py
  idaes/models_extra/carbon_capture/co2_compressor.py
  idaes/models_extra/carbon_capture/tests/test_co2_compressor.py
Labels: Priority:Normal, unit models, backward-compat

#1125 Correcting code owner line for apps/nmpc
  .github/CODEOWNERS
Labels: Priority:Normal, apps

#1130 Add Services Status Badge for Performance Suite
  README.md
Labels: Priority:Normal, testing, approved

#1139 Activing pylint C and I flags in GHA
  .github/workflows/core.yml
Labels: Priority:Normal, testing

#1135 Resolve Pylint rendering failures
  .github/workflows/core.yml
  .pylint/render_report.py
Labels: Priority:High

#1137 Update Python versions in GHA job matrices and documentation
  .github/workflows/core.yml
  .github/workflows/integration.yml
  README.md
  docs/conf.py
  docs/reference_guides/developer/testing.rst
  docs/tutorials/advanced_install/index.rst
  idaes/apps/grid_integration/examples/utils.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/commands/tests/test_commands.py
  idaes/core/dmf/util.py
  idaes/core/surrogate/tests/test_pysmo_surrogate.py
  idaes/tests/prescient/test_prescient.py
  setup.py
Labels: Priority:Normal

#1126 Spring cleaning for dependencies, Pt. 1: The Tree-Shaking
  idaes/core/util/expr_doc.py
  setup.py
Labels: Priority:High

#1142 Creating issue in initialaiztion tester that left Sets attached ot model
  idaes/core/util/testing.py
Labels: bug, Priority:Normal, testing

#976 Implement transport properties for modular property framework
  docs/explanations/components/property_package/general/index.rst
  docs/explanations/components/property_package/general/transport_properties/chapman_enskog.rst
  docs/explanations/components/property_package/general/transport_properties/chung_pure.rst
  docs/explanations/components/property_package/general/transport_properties/eucken.rst
  docs/explanations/components/property_package/general/transport_properties/index.rst
  docs/explanations/components/property_package/general/transport_properties/no_method.rst
  docs/explanations/components/property_package/general/transport_properties/thermal_conductivity_wms.rst
  docs/explanations/components/property_package/general/transport_properties/viscosity_wilke.rst
  docs/reference_guides/initialization/general_initializers.rst
  docs/reference_guides/model_libraries/generic/property_models/index.rst
  idaes/core/base/components.py
  idaes/core/base/phases.py
  idaes/core/base/tests/test_phases.py
  idaes/models/properties/modular_properties/base/generic_property.py
  idaes/models/properties/modular_properties/base/tests/dummy_eos.py
  idaes/models/properties/modular_properties/base/tests/test_generic_property.py
  idaes/models/properties/modular_properties/eos/ceos.py
  idaes/models/properties/modular_properties/eos/ideal.py
  idaes/models/properties/modular_properties/pure/ChapmanEnskog.py
  idaes/models/properties/modular_properties/pure/ChungPure.py
  idaes/models/properties/modular_properties/pure/ConstantProperties.py
  idaes/models/properties/modular_properties/pure/Eucken.py
  idaes/models/properties/modular_properties/pure/__init__.py
  idaes/models/properties/modular_properties/pure/tests/test_ChapmanEnskog.py
  idaes/models/properties/modular_properties/pure/tests/test_ChungPure.py
  idaes/models/properties/modular_properties/pure/tests/test_ConstantProperties.py
  idaes/models/properties/modular_properties/pure/tests/test_Eucken.py
  idaes/models/properties/modular_properties/transport_properties/__init__.py
  idaes/models/properties/modular_properties/transport_properties/no_method.py
  idaes/models/properties/modular_properties/transport_properties/tests/test_no_method.py
  idaes/models/properties/modular_properties/transport_properties/tests/test_shell_and_tube_1D_transport.py
  idaes/models/properties/modular_properties/transport_properties/tests/test_thermal_conductivity_wms.py
  idaes/models/properties/modular_properties/transport_properties/tests/test_viscosity_wilke.py
  idaes/models/properties/modular_properties/transport_properties/thermal_conductivity_wms.py
  idaes/models/properties/modular_properties/transport_properties/viscosity_wilke.py
  idaes/models/unit_models/shell_and_tube_1d.py
  idaes/models_extra/power_generation/properties/natural_gas_PR.py
  idaes/models_extra/power_generation/properties/tests/test_NG_PR.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/common.py
Labels: Priority:Normal

#1144 Minor documentation update for matopt
  docs/explanations/modeling_extensions/matopt/index.rst
  idaes/apps/matopt/README.md
Labels: documentation, Priority:Normal

#1143 Fixing model statistics to work for indexed blocks
  idaes/core/util/model_statistics.py
  idaes/core/util/tests/test_model_statistics.py
Labels: bug, enhancement, Priority:Normal, core

#1147 Simplify error check for ipopt_with_diagnostics test
  idaes/core/util/tests/test_model_diagnostics.py
Labels: bug, Priority:High, core, testing

#1148 Update approach for documenting Config Blocks
  idaes/core/base/process_block.py
  idaes/core/initialization/initializer_base.py
  idaes/core/plugins/variable_replace.py
  setup.py
Labels: documentation, Priority:Normal, core, backward-compat

#1138 Modify or remove get-examples for new repo
  idaes/commands/examples.py
  idaes/commands/tests/test_commands.py
Labels: Priority:High
