Repository IDAES/idaes-pse, pull requests merged in 2023-07, with the labels that each got.

#1220 Fix typos flagged by CI check v1.15.10
  data/resourcedb.json
  idaes/core/dmf/tests/data_files/pitzer/dataset.json
Labels: Priority:High

#1210 Show platform name when binaries not found with bin-platform command
  idaes/commands/extensions.py
  idaes/commands/tests/test_commands.py
Labels: enhancement, Priority:Normal

#1211 Add option to change the initial condition solver.
  idaes/core/solvers/petsc.py
Labels: Priority:Normal

#1226 Deprecating RBF options in ALMAOpy
  docs/explanations/modeling_extensions/surrogate/api/alamopy/alamopy-options.rst
  docs/explanations/modeling_extensions/surrogate/api/alamopy/index.rst
  idaes/core/surrogate/alamopy.py
  idaes/core/surrogate/tests/test_alamopy.py
Labels: bug, Priority:Normal, core, surrogates, backward-compat

#1197 Reformulate solubility_products constraints
  docs/explanations/components/property_package/general_reactions/equil_form.rst
  idaes/models/properties/modular_properties/reactions/equilibrium_forms.py
  idaes/models/properties/modular_properties/reactions/tests/test_equilibrium_forms.py
  idaes/models/properties/modular_properties/reactions/tests/test_solubility_product_verification.py
Labels: enhancement, Priority:Normal, property packages, WaterTAP

#1234 global search and replace pyomo.core.expr.current -> pyomo.core.expr (ref pyomo PR #2910)
  idaes/apps/uncertainty_propagation/sens.py
  idaes/core/util/model_statistics.py
  idaes/models_extra/gas_distribution/properties/natural_gas.py
  idaes/models_extra/gas_distribution/unit_models/pipeline.py
  idaes/models_extra/power_generation/unit_models/steamheater.py
  idaes/models_extra/power_generation/unit_models/waterwall_section.py
  setup.py
Labels: Priority:High, backward-compat, pyomo
