Repository IDAES/idaes-pse, pull requests merged in 2023-05, with the labels that each got.

#1160 Extractor unit model for minerals processing
  docs/index.rst
  docs/reference_guides/initialization/specific_initializers.rst
  docs/reference_guides/model_libraries/generic/unit_models/heater.rst
  docs/reference_guides/model_libraries/generic/unit_models/index.rst
  docs/reference_guides/model_libraries/generic/unit_models/mscontactor.rst
  idaes/core/base/control_volume0d.py
  idaes/core/base/control_volume_base.py
  idaes/core/base/unit_model.py
  idaes/core/initialization/block_triangularization.py
  idaes/core/initialization/tests/test_block_triangularization.py
  idaes/models/unit_models/__init__.py
  idaes/models/unit_models/heat_exchanger.py
  idaes/models/unit_models/mscontactor.py
  idaes/models/unit_models/tests/test_feed.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_mscontactor.py
Labels: enhancement, Priority:Normal, unit models, WaterTAP, PrOMMiS

#1178 Changes related to finalizing power plant costing module
  docs/reference_guides/model_libraries/power_generation/costing/power_plant_costing_netl.rst
  idaes/models_extra/power_generation/costing/BB_costing_data.json
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
  idaes/models_extra/power_generation/costing/tests/test_NGCC_capcost.py
  idaes/models_extra/power_generation/costing/tests/test_power_plant_capcost.py
Labels: Priority:Normal

#1188 Correct argument type for ParamSweeper construction in pipeline tests
  idaes/models_extra/gas_distribution/unit_models/tests/test_compressor.py
  idaes/models_extra/gas_distribution/unit_models/tests/test_pipeline.py
Labels: bug, Priority:High, testing

#1185 OMLT documentation
  docs/explanations/modeling_extensions/surrogate/api/omlt-keras/index.rst
  docs/explanations/modeling_extensions/surrogate/api/omlt-keras/omlt-keras-options.rst
Labels: documentation, Priority:Normal

#1187 Address Pyomo 6.6 compatibility issues
  idaes/core/surrogate/tests/test_pysmo_surrogate.py
  idaes/models/properties/general_helmholtz/tests/test_parameter_util.py
  idaes/models/properties/modular_properties/eos/tests/test_ideal.py
  setup.py
Labels: Priority:High, testing

#1133 Spring cleaning for dependencies, Pt. 2: The Tree-Chopping
  .github/workflows/integration.yml
  README.md
  docs/explanations/modeling_extensions/surrogate/api/omlt-keras/index.rst
  docs/how_to_guides/index.rst
  docs/how_to_guides/opt_dependencies.rst
  docs/how_to_guides/versioned_idaes_install.rst
  docs/reference_guides/apps/grid_integration/index.rst
  docs/tutorials/getting_started/index.rst
  docs/tutorials/getting_started/opt_dependencies.rst
  idaes/commands/__init__.py
  idaes/conftest.py
  idaes/core/dmf/util.py
  idaes/core/ui/fsvis/tests/test_model_server.py
  idaes/core/util/convergence/convergence_base.py
  idaes/tests/test_headers.py
  pytest.ini
  requirements-dev.txt
  setup.py
Labels: Priority:High

#1195 Update pyomo requirement to 6.6.1
  setup.py
Labels: Priority:High

#1193 Add encoding to read helmholtz references
  idaes/models/properties/general_helmholtz/components/parameters/__init__.py
Labels: bug, Priority:High

#1194 Add Propane Transport Properties
  idaes/models/properties/general_helmholtz/components/parameters/propane.json
  idaes/models/properties/general_helmholtz/components/parameters/propane.py
  idaes/models/properties/general_helmholtz/components/parameters/propane_expressions_eos.nl
  idaes/models/properties/general_helmholtz/components/parameters/propane_expressions_tcx.nl
  idaes/models/properties/general_helmholtz/components/parameters/propane_expressions_visc.nl
  idaes/models/properties/general_helmholtz/components/parameters/propane_parameters.json
  idaes/models/properties/general_helmholtz/helmholtz_parameters.py
  idaes/models/properties/general_helmholtz/helmholtz_state.py
  idaes/models/properties/general_helmholtz/tests/test_functions_unit.py
Labels: enhancement

#1192 Surface tension fix for over critical
  idaes/models/properties/general_helmholtz/components/parameters/co2_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/h2o_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/propane_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/r1234ze_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/r125_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/r134a_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/r227ea_expressions_st.nl
  idaes/models/properties/general_helmholtz/components/parameters/r32_expressions_st.nl
  idaes/models/properties/general_helmholtz/expressions/surface_tension_type01.py
Labels: bug, Priority:High
