Repository IDAES/idaes-pse, pull requests merged in 2023-08, with the labels that each got.

#1229 Add support for heterogeneous reactions in MSContactor
  docs/reference_guides/model_libraries/generic/unit_models/mscontactor.rst
  idaes/models/unit_models/mscontactor.py
  idaes/models/unit_models/tests/test_mscontactor.py
Labels: enhancement, Priority:Normal, unit models, PrOMMiS

#1236 Adding deprecation warning for has_phase_equilibrium but only 1 phase
  idaes/core/base/control_volume0d.py
  idaes/core/base/control_volume1d.py
  idaes/core/base/tests/test_control_volume_0d.py
  idaes/core/base/tests/test_control_volume_1d.py
Labels: Priority:High, core, backward-compat

#1225 Add CI job for compatibility testing
  .github/workflows/core.yml
Labels: Priority:High, backward-compat

#1230 Add properties and minor fixes for property sets
  idaes/core/base/property_meta.py
  idaes/core/base/property_set.py
  idaes/core/base/tests/test_property_set.py
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
Labels: Priority:Normal

#1237 Contributes script to install IDAES and COIN solvers on Google Colab
  .github/CODEOWNERS
  scripts/colab_helper.py
Labels: Priority:Normal

#1243 MS Contactor improvements
  idaes/models/unit_models/mscontactor.py
Labels: bug, Priority:Normal, unit models, PrOMMiS

#1242 Function Scoping Fixes
  idaes/models/unit_models/mixer.py
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/tests/test_separator.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_module_simple.py
Labels: bug, Priority:High, unit models

#1239 Remove some logger config stuff
  docs/reference_guides/configuration.rst
  idaes/commands/config.py
  idaes/commands/tests/test_commands.py
  idaes/config.py
  idaes/core/base/tests/test_control_volume_0d.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/base/tests/test_costing_base.py
  idaes/core/base/tests/test_property_base.py
  idaes/core/base/tests/test_reaction_base.py
  idaes/tests/test_config.py
Labels: Priority:High

#1246 Update the Pyomo tag to the 6.6.2 release
  idaes/core/base/tests/test_var_like_expression.py
  idaes/core/base/var_like_expression.py
  idaes/models/properties/modular_properties/eos/tests/test_enrtl.py
  idaes/models/properties/modular_properties/eos/tests/test_ideal.py
  idaes/models/properties/modular_properties/phase_equil/tests/test_henry.py
  idaes/models/unit_models/tests/test_mscontactor.py
  setup.py
Labels: Priority:High

#1247 Remove (part of) the remaining Pyomo 6.6.2 deprecations
  idaes/core/plugins/simple_equality_eliminator.py
  idaes/core/plugins/variable_replace.py
  idaes/core/surrogate/pysmo/utils.py
  idaes/core/util/expr_doc.py
  idaes/core/util/scaling.py
Labels: Priority:High

#1228 DiagnosticsToolbox
  docs/explanations/index.rst
  docs/explanations/model_diagnostics/diagnostics_workflow.png
  docs/explanations/model_diagnostics/index.rst
  docs/explanations/modeling_extensions/diagnostics/index.rst
  docs/index.rst
  docs/reference_guides/core/util/diagnostics/degeneracy_hunter.rst
  docs/reference_guides/core/util/diagnostics/diagnostics_toolbox.rst
  docs/reference_guides/core/util/model_diagnostics.rst
  idaes/core/util/__init__.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/model_statistics.py
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_model_statistics.py
Labels: enhancement, help wanted, Priority:High, core, diagnostics

#1235 PETSc Tweaks
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
Labels: enhancement, Priority:Normal, backward-compat, PETSc

#1199 Update IDAES-EXT version
  .github/actions/run-examples/examples_for_idaes_ci.py
  idaes/config.py
Labels: Priority:Normal

#1244 Turn on Pylint check for closures in loop
  .pylint/pylintrc
  idaes/core/base/costing_base.py
  idaes/models/unit_models/mscontactor.py
  idaes/models_extra/column_models/util.py
Labels: Priority:High

#1254 Add version constraint to exclude pandas 2.1 as a workaround for Pysmo test failures
  setup.py
Labels: Priority:High
