Repository IDAES/idaes-pse, pull requests merged in 2023-09, with the labels that each got.

#1251 Fix PETSc logging issue
  idaes/config.py
Labels: Priority:High

#1252 Fixing trying to access metadata via config block
  docs/reference_guides/model_libraries/generic/control/pid.rst
  docs/reference_guides/model_libraries/generic/unit_models/valve.rst
  idaes/core/base/control_volume0d.py
  idaes/core/base/property_base.py
  idaes/models/unit_models/feed.py
  idaes/models/unit_models/flash.py
  idaes/models/unit_models/gibbs_reactor.py
  idaes/models/unit_models/heat_exchanger.py
  idaes/models/unit_models/heat_exchanger_1D.py
  idaes/models/unit_models/heat_exchanger_lc.py
  idaes/models/unit_models/heat_exchanger_ntu.py
  idaes/models/unit_models/mixer.py
  idaes/models/unit_models/mscontactor.py
  idaes/models/unit_models/plug_flow_reactor.py
  idaes/models/unit_models/pressure_changer.py
  idaes/models/unit_models/product.py
  idaes/models/unit_models/separator.py
  idaes/models/unit_models/shell_and_tube_1d.py
  idaes/models/unit_models/statejunction.py
  idaes/models/unit_models/valve.py
  idaes/models_extra/column_models/condenser.py
  idaes/models_extra/column_models/plate_heat_exchanger.py
  idaes/models_extra/column_models/reboiler.py
  idaes/models_extra/column_models/tray.py
  idaes/models_extra/power_generation/unit_models/helm/condenser_ntu.py
Labels: bug, Priority:High, core, unit models

#1259 Fixing handling of useDefault in lumped capacitance HX model
  idaes/models/unit_models/heat_exchanger_lc.py
  idaes/models/unit_models/tests/test_heat_exchanger_lc.py
Labels: bug, Priority:High, unit models

#1267 Setting pandas!=2.1.0
  setup.py
Labels: bug, Priority:Normal, dependencies, surrogates, PySMO

#1269 UI Page
  .readthedocs.yml
  docs/explanations/components/ui/index.rst
  docs/how_to_guides/opt_dependencies.rst
  docs/index.rst
  docs/reference_guides/index.rst
Labels: documentation

#1255 SOC changes
  idaes/models_extra/power_generation/unit_models/soc_submodels/channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/common.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/contact_resistor.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/porous_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_cell.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/solid_oxide_module_simple.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_contact_resistor.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_interconnect.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_porous_conductive_slab.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_solid_oxide_cell.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_triple_phase_boundary.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/triple_phase_boundary.py
Labels: Priority:Normal

#1260 Active flag for PETSc
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
Labels: Priority:Normal
