Repository IDAES/idaes-pse, pull requests merged in 2023-02, with the labels that each got.

#1070 Add option for ALAMO model as expression
  idaes/core/surrogate/alamopy.py
  idaes/core/surrogate/tests/test_alamopy.py
  idaes/core/surrogate/tests/test_pysmo_surrogate.py
Labels: enhancement, Priority:High, testing

#1076 Add Ipopt L1 solver factory
  idaes/config.py
  idaes/core/solvers/ipopt_l1.py
  idaes/core/solvers/tests/test_solver_config.py
  idaes/core/solvers/tests/test_solvers.py
Labels: enhancement

#997 Scaling Issues with New Pyomo Solver Writer
  idaes/apps/uncertainty_propagation/sens.py
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
  idaes/core/util/tags.py
  idaes/core/util/tests/test_misc.py
  idaes/models/flowsheets/demo_flowsheet.py
  idaes/models/properties/activity_coeff_models/BTX_activity_coeff_VLE.py
  idaes/models/properties/activity_coeff_models/activity_coeff_prop_pack.py
  idaes/models/properties/activity_coeff_models/tests/test_ideal_ideal_FcTP.py
  idaes/models/properties/cubic_eos/cubic_prop_pack.py
  idaes/models/properties/modular_properties/base/tests/test_generic_property_integration.py
  idaes/models/properties/modular_properties/phase_equil/tests/test_henry.py
  idaes/models/properties/modular_properties/reactions/tests/test_equilibrium_constant.py
  idaes/models/properties/modular_properties/reactions/tests/test_equilibrium_forms.py
  idaes/models_extra/column_models/tests/test_MEAsolvent_column.py
  idaes/models_extra/column_models/tests/test_plate_heat_exchanger.py
  idaes/models_extra/column_models/tests/test_reboiler.py
  idaes/models_extra/column_models/tests/test_tray_column.py
  idaes/models_extra/gas_distribution/properties/tests/test_natural_gas.py
  idaes/models_extra/power_generation/flowsheets/supercritical_power_plant/boiler_subflowsheet_build.py
  idaes/models_extra/power_generation/properties/tests/test_NG_PR.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_interconnect.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_thin.py
  setup.py
Labels: bug, Priority:High

#1072 Moving bed with bidirectional spatial discretization
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/moving_bed.rst
  idaes/models_extra/gas_solid_contactors/unit_models/moving_bed.py
  idaes/models_extra/gas_solid_contactors/unit_models/tests/test_MB.py
Labels: Priority:High, approved

#1085 Rework control volume code to remove unneeded terms.
  idaes/core/base/control_volume0d.py
  idaes/core/base/control_volume1d.py
  idaes/core/base/control_volume_base.py
  idaes/core/base/tests/test_control_volume_0d.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/util/model_statistics.py
  idaes/models/properties/modular_properties/eos/ceos.py
Labels: bug, Priority:Normal, core, property packages

#1081 Fix NumPy array creation error by specifying object type
  idaes/core/surrogate/pysmo/kriging.py
  idaes/core/surrogate/pysmo/polynomial_regression.py
  idaes/core/surrogate/pysmo/radial_basis_function.py
  idaes/core/surrogate/tests/test_pysmo_surrogate.py
Labels: Priority:Normal, surrogates

#968 Pid improvements
  docs/reference_guides/model_libraries/generic/control/pid.rst
  idaes/core/solvers/tests/test_petsc_pid.py
  idaes/core/util/tests/test_pid_initialization.py
  idaes/models/control/__init__.py
  idaes/models/control/controller.py
  idaes/models/control/tests/test_antiwindup.py
  idaes/models/control/tests/test_controller.py
  idaes/models/control/tests/test_pid_pump.py
  idaes/models/control/tests/test_steam_tank_pressure.py
  idaes/models/unit_models/valve.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/steam_cycle_flowsheet.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/tests/test_subcritical_flowsheets.py
Labels: Priority:Normal

#1087 Improving some expression tests
  idaes/models/properties/modular_properties/eos/enrtl.py
  idaes/models/properties/modular_properties/eos/enrtl_reference_states.py
  idaes/models/properties/modular_properties/eos/tests/test_enrtl.py
  idaes/models/properties/modular_properties/eos/tests/test_ideal.py
  idaes/models/properties/modular_properties/reactions/tests/test_equilibrium_constant.py
  idaes/models/properties/modular_properties/state_definitions/FPhx.py
  idaes/models/properties/modular_properties/state_definitions/FTPx.py
  idaes/models/properties/modular_properties/state_definitions/FcPh.py
  idaes/models/properties/modular_properties/state_definitions/FcTP.py
  idaes/models/properties/modular_properties/state_definitions/FpcTP.py
Labels: Priority:Normal, property packages, testing

#1054 [Grid Integration] Allow a generator to be "re-typed" in grid integration
  idaes/apps/grid_integration/coordinator.py
  idaes/apps/grid_integration/tests/bidder_integration_test_plugin.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_integration.py
  setup.py
Labels: Priority:High, DISPATCHES

#1083 Resolving OMLT v1.0 dependency issues
  idaes/core/surrogate/keras_surrogate.py
  idaes/core/surrogate/surrogate_block.py
  idaes/core/surrogate/tests/test_keras_surrogate.py
  setup.py
Labels: Priority:Normal, dependencies, backward-compat, DISPATCHES

#1019 Update grid integration
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/model_data.py
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_model_data.py
Labels: Priority:High, DISPATCHES

#970 Making selecting and unselecting elements using the shift key smoother
  idaes/core/ui/fsvis/static/js/paper.js
Labels: Priority:Normal

#1091 Better initial guesses when initializing Control Volumes
  idaes/core/base/control_volume0d.py
  idaes/core/base/control_volume1d.py
  idaes/core/base/control_volume_base.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/base/tests/test_control_volume_base.py
  idaes/models/unit_models/tests/test_pressure_changer.py
  idaes/models_extra/power_generation/properties/flue_gas_ideal.py
Labels: enhancement, Priority:Normal, core

#1092 Fixing check for kaug in uncertainty tests
  idaes/apps/uncertainty_propagation/tests/test_uncertainties.py
Labels: bug, Priority:Normal, testing

#1050 Improvements to distillation unit model
  idaes/models_extra/column_models/condenser.py
  idaes/models_extra/column_models/reboiler.py
  idaes/models_extra/column_models/tests/test_tray_column.py
  idaes/models_extra/column_models/tests/test_utilities.py
  idaes/models_extra/column_models/tray.py
  idaes/models_extra/column_models/tray_column.py
  idaes/models_extra/column_models/util.py
Labels: enhancement, Priority:Normal, unit models

#1089 Update Pyomo tag to 6.5.0 and update Incidence Analysis method name
  idaes/apps/caprese/categorize.py
  idaes/core/initialization/block_triangularization.py
  setup.py
Labels: Priority:High, dependencies, backward-compat

#1096 Updated `set_param_from_config` method to use `set_value`
  idaes/core/util/misc.py
  idaes/core/util/tests/test_misc.py
Labels: enhancement, Priority:Low, core

#1097 Deprecating categorize_dae_variables
  idaes/apps/caprese/categorize.py
Labels: Priority:Normal, backward-compat, apps

#1079 New mixed phase property functions for Helmholtz EoS.
  idaes/commands/util/tests/test_download_bin.py
  idaes/config.py
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
  idaes/models/properties/general_helmholtz/helmholtz_state.py
  idaes/models/properties/general_helmholtz/tests/test_functions_unit.py
  idaes/models/properties/general_helmholtz/tests/test_with_harness.py
Labels: Priority:High

#1086 Minor updates to install docs
  README.md
  docs/conf.py
  docs/tutorials/getting_started/binaries.rst
  docs/tutorials/getting_started/index.rst
  docs/tutorials/getting_started/install_templates/extensions.md
  docs/tutorials/getting_started/install_templates/idaes_data.md
  docs/tutorials/getting_started/install_templates/quickstart.md
  docs/tutorials/getting_started/install_templates/run_tests.md
  docs/tutorials/getting_started/linux.rst
  docs/tutorials/getting_started/mac_osx.rst
  docs/tutorials/getting_started/windows.rst
  idaes/config.py
  idaes/models/properties/modular_properties/eos/ceos_common.py
Labels: documentation, Priority:Normal

#1105 Change update step for advanced install instructions
  docs/tutorials/advanced_install/index.rst
Labels: Priority:Normal

#1104 Adding more pylint checks
  .github/workflows/core.yml
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/forecaster.py
  idaes/apps/grid_integration/model_data.py
  idaes/apps/helmet/BasisFunctions.py
  idaes/apps/helmet/GAMSDataWrite.py
  idaes/commands/examples.py
  idaes/core/dmf/codesearch.py
  idaes/core/initialization/initializer_base.py
  idaes/core/surrogate/plotting/sm_plotter.py
  idaes/core/ui/fsvis/errors.py
  idaes/core/ui/fsvis/persist.py
  idaes/core/util/convergence/mpi_utils.py
  idaes/core/util/exceptions.py
  idaes/core/util/initialization.py
  idaes/models/costing/SSLW.py
  idaes/models/properties/modular_properties/base/generic_property.py
  idaes/models/properties/modular_properties/base/generic_reaction.py
  idaes/models_extra/column_models/properties/MEA_vapor.py
  idaes/models_extra/column_models/solvent_column.py
  idaes/models_extra/gas_distribution/unit_models/compressor.py
  idaes/models_extra/gas_distribution/unit_models/node.py
  idaes/models_extra/gas_distribution/unit_models/pipeline.py
  idaes/models_extra/gas_solid_contactors/properties/methane_iron_OC_reduction/gas_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/methane_iron_OC_reduction/hetero_reactions.py
  idaes/models_extra/gas_solid_contactors/properties/methane_iron_OC_reduction/solid_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/gas_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/hetero_reactions.py
  idaes/models_extra/gas_solid_contactors/properties/oxygen_iron_OC_oxidation/solid_phase_thermo.py
  idaes/models_extra/gas_solid_contactors/unit_models/bubbling_fluidized_bed.py
  idaes/models_extra/gas_solid_contactors/unit_models/fixed_bed_1D.py
  idaes/models_extra/gas_solid_contactors/unit_models/moving_bed.py
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
  idaes/models_extra/power_generation/flowsheets/subcritical_power_plant/subcritical_power_plant.py
  idaes/models_extra/power_generation/unit_models/waterwall_section.py
Labels: Priority:Normal, testing
