Repository IDAES/idaes-pse, pull requests merged in 2023-10, with the labels that each got.

#1280 Fix typos being detected after CI check update
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
Labels: Priority:High

#1256 SVD Toolbox for diagnostics
  docs/explanations/model_diagnostics/degeneracy_hunter.rst
  docs/explanations/model_diagnostics/index.rst
  docs/explanations/model_diagnostics/svd_analysis.rst
  docs/reference_guides/core/util/diagnostics/degeneracy_hunter.rst
  docs/reference_guides/core/util/diagnostics/degeneracy_hunter_legacy.rst
  docs/reference_guides/core/util/diagnostics/svd_toolbox.rst
  docs/reference_guides/core/util/model_diagnostics.rst
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: enhancement, Priority:Normal, core, WIP, diagnostics

#1266 Addressing Demo Flowsheet (Scaling) Failures
  idaes/models/flowsheets/demo_flowsheet.py
  idaes/models/flowsheets/tests/test_demo_flowsheet.py
Labels: Priority:Normal, WIP

#1232 Add fixed bed 0D TSA unit model
  docs/reference_guides/model_libraries/models_extra/index.rst
  docs/reference_guides/model_libraries/models_extra/temperature_swing_adsorption/TSA_IDAES_Implementation.png
  docs/reference_guides/model_libraries/models_extra/temperature_swing_adsorption/fixed_bed_tsa0d.rst
  docs/reference_guides/model_libraries/models_extra/temperature_swing_adsorption/tsa_cycle.png
  idaes/models_extra/temperature_swing_adsorption/__init__.py
  idaes/models_extra/temperature_swing_adsorption/costing/costing_params_dac_electric_boiler.json
  idaes/models_extra/temperature_swing_adsorption/costing/costing_params_dac_retrofit_ngcc.json
  idaes/models_extra/temperature_swing_adsorption/costing/dac_costing.py
  idaes/models_extra/temperature_swing_adsorption/fixed_bed_tsa0d.py
  idaes/models_extra/temperature_swing_adsorption/initializer.py
  idaes/models_extra/temperature_swing_adsorption/tests/test_fixed_bed_tsa0d.py
  idaes/models_extra/temperature_swing_adsorption/tests/test_fixed_bed_tsa0d_costing.py
  idaes/models_extra/temperature_swing_adsorption/util.py
Labels: Priority:Normal, WIP

#1279 Add link to optional dependencies installation guide
  docs/how_to_guides/opt_dependencies.rst
  docs/tutorials/getting_started/index.rst
Labels: Priority:High
