Repository IDAES/idaes-pse, pull requests merged in 2023-12, with the labels that each got.

#1292 Update the Pyomo tag to the 6.7.0 release
  setup.py
Labels: Priority:High

#1288 Fix methods in SVD Toolbox
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: Priority:Normal

#1295 Fixing bug in TSA tests
  idaes/models_extra/temperature_swing_adsorption/fixed_bed_tsa0d.py
  idaes/models_extra/temperature_swing_adsorption/tests/test_fixed_bed_tsa0d.py
  idaes/models_extra/temperature_swing_adsorption/util.py
Labels: bug, Priority:Normal, testing, models_extra

#1291 Add support for dynamics to MS Contactor
  docs/reference_guides/model_libraries/generic/unit_models/mscontactor.rst
  idaes/models/unit_models/mscontactor.py
  idaes/models/unit_models/tests/test_mscontactor.py
Labels: enhancement, Priority:Normal, unit models, PrOMMiS

#1303 Fix SOC sign error
  idaes/models_extra/power_generation/unit_models/soc_submodels/channel.py
  idaes/models_extra/power_generation/unit_models/soc_submodels/tests/test_herring_replication_interconnect.py
Labels: Priority:High

#1298 Add custom sampling option to PySMO
  docs/explanations/modeling_extensions/surrogate/sampling/index.rst
  docs/explanations/modeling_extensions/surrogate/sampling/pysmo_custom.rst
  idaes/core/surrogate/pysmo/sampling.py
  idaes/core/surrogate/pysmo/tests/test_sampling.py
Labels: Priority:Normal

#1304 Improve model for thickeners
  docs/reference_guides/model_libraries/generic/unit_models/solid_liquid/thickener0d.rst
  idaes/models/unit_models/solid_liquid/tests/test_thickener.py
  idaes/models/unit_models/solid_liquid/thickener.py
Labels: enhancement, Priority:Normal, unit models, backward-compat, PrOMMiS
