Repository IDAES/idaes-pse, pull requests merged in 2024-11, with the labels that each got.

#1454 Diagnostics tool for ill-posed constraints
  idaes/core/scaling/custom_scaler_base.py
  idaes/core/util/misc.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_misc.py
  idaes/core/util/tests/test_model_diagnostics.py
  setup.py
Labels: enhancement, Priority:High, diagnostics

#1526 New URL for Downloads Badge
  README.md
Labels: Priority:Normal

#1523 Bumping the IDAES tag of Pyomo to check for issues
  setup.py
Labels: Priority:High

#1533 Prune down unused dev dependencies
  requirements-dev.txt
Labels: Priority:Normal

#1535 removed jenkinsfile and entire docker folder
  Jenkinsfile
  docker/README.md
  docker/idaes-jupyterhub/Dockerfile
  docker/idaes-jupyterhub/README.md
  docker/ubuntu-conda/Dockerfile
  docker/ubuntu-conda/README-build.md
  docker/ubuntu-conda/README.md
Labels: Priority:Normal

#1519 Deprecate old Cubic EoS
  docs/reference_guides/model_libraries/generic/property_models/ceos.rst
  idaes/models/properties/cubic_eos/cubic_prop_pack.py
  idaes/models/properties/cubic_eos/tests/test_BT_example.py
  idaes/models/properties/cubic_eos/tests/test_cubic_prop_pack.py
Labels: Priority:High, backward-compat, deprecation

#1513 updated all mentions/use of anaconda/miniconda to reflect usage of mi…
  .github/workflows/core.yml
  .github/workflows/integration.yml
  README.md
  docs/reference_guides/developer/devsw.rst
  docs/tutorials/advanced_install/index.rst
  docs/tutorials/getting_started/index.rst
  docs/tutorials/getting_started/linux.rst
  docs/tutorials/getting_started/mac_osx.rst
  docs/tutorials/getting_started/windows.rst
Labels: Priority:High

#1543 Update conda install commands after idaes-pse was added to conda-forge
  .github/workflows/integration.yml
  docs/tutorials/getting_started/install_templates/conda_idaes_pse.txt
  docs/tutorials/getting_started/install_templates/quickstart.txt
Labels: documentation, Priority:High

#1534 Add a mapping for Pop!_OS (default for System76 laptops) to get-extensions
  idaes/config.py
Labels: Priority:High

#1545 Shorten names of files causing installation errors (#1540)
  idaes/core/surrogate/tests/data/onnx_models/net_Calcite_ST.onnx
  idaes/core/surrogate/tests/data/onnx_models/net_Calcite_ST_idaes_info.json
  idaes/core/surrogate/tests/test_onnx_surrogate.py
Labels: Priority:High

#1378 1D Membrane Model for CO2 Capture and Utilization
  docs/reference_guides/model_libraries/models_extra/index.rst
  docs/reference_guides/model_libraries/models_extra/membrane_model/1d_membrane.rst
  idaes/models_extra/co2_capture_and_utilization/__init__.py
  idaes/models_extra/co2_capture_and_utilization/unit_models/README.md
  idaes/models_extra/co2_capture_and_utilization/unit_models/__init__.py
  idaes/models_extra/co2_capture_and_utilization/unit_models/membrane_1d.py
  idaes/models_extra/co2_capture_and_utilization/unit_models/tests/__init__.py
  idaes/models_extra/co2_capture_and_utilization/unit_models/tests/test_membrane_1d.py
Labels: Priority:Normal, models_extra, CCU

#1517 Adding StreamScaler unit model, along with the test and rst file.
  docs/build.py
  docs/reference_guides/model_libraries/generic/unit_models/index.rst
  docs/reference_guides/model_libraries/generic/unit_models/stream_scaler.rst
  idaes/models/unit_models/__init__.py
  idaes/models/unit_models/stream_scaler.py
  idaes/models/unit_models/tests/test_stream_scaler.py
Labels: Priority:Normal
