Repository IDAES/idaes-pse, pull requests merged in 2024-08, with the labels that each got.

#1451 Add code references to gas solid contactors docs
  docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/dyn_TGA_example.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_BFB_OC_oxidation.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_BFB_methane_combustion.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/flowsheets/ss_MB_methane_combustion.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/bubbling_fluidized_bed.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/fixed_bed_0D.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/fixed_bed_1D.rst
  docs/reference_guides/model_libraries/gas_solid_contactors/unit_models/moving_bed.rst
Labels: Priority:Normal

#1407 Renewable + PEM Parameterized Bidder
  docs/reference_guides/apps/grid_integration/Bidder.rst
  docs/reference_guides/apps/grid_integration/Tracker.rst
  docs/reference_guides/apps/grid_integration/index.rst
  idaes/apps/grid_integration/bidder.py
  idaes/apps/grid_integration/forecaster.py
  idaes/apps/grid_integration/tests/test_PEM_Parameterized_bidder.py
  idaes/apps/grid_integration/tests/test_perfectforecaster.py
Labels: Priority:Normal, DISPATCHES

#1467 Remove support for Python 3.8
  .github/workflows/core.yml
  .github/workflows/integration.yml
  README.md
  docs/conf.py
  docs/explanations/faq.rst
  setup.py
Labels: Priority:High

#1460 Repair erroneous units for material_holdup in CV0D when mass basis defined
  idaes/core/base/control_volume0d.py
  idaes/core/base/flowsheet_model.py
  idaes/core/base/tests/test_control_volume_0d.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/util/testing.py
Labels: Priority:High, WaterTAP

#1401 Keras file format updates
  .github/actions/run-examples/examples_for_idaes_ci.py
  idaes/core/surrogate/keras_surrogate.py
  idaes/core/surrogate/plotting/tests/keras_surrogate/idaes_keras_model.keras
  idaes/core/surrogate/plotting/tests/keras_surrogate/keras_metadata.pb
  idaes/core/surrogate/plotting/tests/keras_surrogate/saved_model.pb
  idaes/core/surrogate/plotting/tests/keras_surrogate/variables/variables.data-00000-of-00001
  idaes/core/surrogate/plotting/tests/keras_surrogate/variables/variables.index
  idaes/core/surrogate/tests/data/create_keras_models.py
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.h5
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.json
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.keras
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_relu.weights.h5
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.h5
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.json
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.keras
  idaes/core/surrogate/tests/data/keras_models/PT_data_2_10_10_2_sigmoid.weights.h5
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.h5
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.json
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.keras
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_relu.weights.h5
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.h5
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.json
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.keras
  idaes/core/surrogate/tests/data/keras_models/T_data_1_10_10_2_sigmoid.weights.h5
  idaes/core/surrogate/tests/test_keras_surrogate.py
  idaes/models_extra/power_generation/properties/sofc/sofc_keras_surrogate.py
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/idaes_keras_model.keras
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/saved_model.pb
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/variables/variables.data-00000-of-00001
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/variables/variables.index
  idaes/models_extra/power_generation/properties/tests/test_sofc_surrogates.py
  setup.py
Labels: Priority:High

#1473 Bump extensions version to 3.4.2
  idaes/commands/extensions.py
  idaes/config.py
Labels: Priority:Normal

#1414 Add reference to constructing class in ProcessBlock
  idaes/core/base/process_block.py
  idaes/core/base/tests/test_process_block.py
Labels: Priority:High, WaterTAP

#1465 Update Pyomo requirement to 6.8.0 release
  idaes/core/surrogate/pysmo/polynomial_regression.py
  idaes/core/surrogate/pysmo/tests/test_polynomial_regression.py
  idaes/core/surrogate/pysmo/tests/test_radial_basis_function.py
  setup.py
Labels: Priority:High

#1472 PySMO: fix warnings
  idaes/core/surrogate/pysmo/kriging.py
  idaes/core/surrogate/pysmo/polynomial_regression.py
  idaes/core/surrogate/pysmo/radial_basis_function.py
  idaes/core/surrogate/pysmo/sampling.py
  idaes/core/surrogate/pysmo/tests/test_kriging.py
  idaes/core/surrogate/pysmo/tests/test_polynomial_regression.py
  idaes/core/surrogate/pysmo/tests/test_radial_basis_function.py
  idaes/core/surrogate/pysmo/tests/test_sampling.py
  idaes/core/surrogate/pysmo/tests/test_sampling_modified.py
  idaes/core/surrogate/pysmo_surrogate.py
Labels: Priority:Normal, warnings

#1475 Remove SOFC Keras Surrogates And Tests
  idaes/models_extra/power_generation/properties/sofc/sofc_keras_surrogate.py
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/idaes_info.json
  idaes/models_extra/power_generation/properties/sofc/sofc_surrogate_data/idaes_keras_model.keras
  idaes/models_extra/power_generation/properties/tests/test_sofc_surrogates.py
Labels: Priority:High, surrogates

#1466 add UI return, then visualize() can return now
  idaes/core/base/flowsheet_model.py
Labels: Priority:Normal

#1478 Updating BTX param with units
  idaes/models/properties/activity_coeff_models/BTX_activity_coeff_VLE.py
Labels: Priority:Normal, property packages
