Repository IDAES/idaes-pse, pull requests merged in 2024-09, with the labels that each got.

#1486 Pin typos version to latest currently available tag v1.24.5
  .github/CODEOWNERS
  .github/workflows/core.yml
  .github/workflows/typos.toml
  idaes/core/initialization/tests/test_initializer_base.py
Labels: Priority:High

#1482 Add basis to conc example on property naming conventions docs
  docs/explanations/conventions.rst
Labels: bug, documentation, Priority:High

#1487 Fixing scaling bug related to external functions with string arguments
  idaes/core/util/scaling.py
  idaes/core/util/tests/test_scaling.py
Labels: bug, user request, Priority:Normal, core
