Repository IDAES/idaes-pse, pull requests merged in 2024-03, with the labels that each got.

#1342 Fix calculate_derivatives for PETSc
  idaes/core/solvers/petsc.py
  idaes/core/solvers/tests/test_petsc.py
Labels: Priority:High

#1360 Make `DegeneracyHunter` tests more robust wrt different solutions
  .github/actions/setup-idaes/action.yml
  idaes/core/util/tests/test_model_diagnostics.py
Labels: Priority:High

#1361 Add upper versions constraints for numpy and pandas
  setup.py
Labels: Priority:High, dependencies

#1373 Add constraint to exclude TensorFlow 2.16.1 and above
  setup.py
Labels: Priority:High, dependencies

#1366 Update imports of `native_types` and `pyomo_constant_types` in scaling module
  idaes/core/util/scaling.py
Labels: Priority:Normal

#1362 Restore ability to run pytest on individual files or directories
  .github/workflows/core.yml
  .github/workflows/integration.yml
  idaes/conftest.py
  pytest.ini
Labels: Priority:Normal

#1377 Tweaks to convergence tester
  idaes/core/util/model_diagnostics.py
  idaes/core/util/parameter_sweep.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_parameter_sweep.py
Labels: bug, enhancement, Priority:Normal, testing

#1375 Add diagnostics tests for all unit models
  idaes/__init__.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/models/properties/examples/saponification_thermo.py
  idaes/models/unit_models/heat_exchanger.py
  idaes/models/unit_models/tests/test_cstr.py
  idaes/models/unit_models/tests/test_equilibrium_reactor.py
  idaes/models/unit_models/tests/test_feed.py
  idaes/models/unit_models/tests/test_feed_flash.py
  idaes/models/unit_models/tests/test_flash.py
  idaes/models/unit_models/tests/test_heat_exchanger.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_heat_exchanger_lc.py
  idaes/models/unit_models/tests/test_heater.py
  idaes/models/unit_models/tests/test_hx_ntu.py
  idaes/models/unit_models/tests/test_mixer.py
  idaes/models/unit_models/tests/test_pfr.py
  idaes/models/unit_models/tests/test_pressure_changer.py
  idaes/models/unit_models/tests/test_product.py
  idaes/models/unit_models/tests/test_rstoic.py
  idaes/models/unit_models/tests/test_separator.py
  idaes/models/unit_models/tests/test_shell_and_tube_1D.py
  idaes/models/unit_models/tests/test_statejunction.py
  idaes/models/unit_models/tests/test_translator.py
  idaes/models/unit_models/tests/test_valve.py
Labels: Priority:Normal, testing, unit models
