Repository IDAES/idaes-pse, pull requests merged in 2024-05, with the labels that each got.

#1385 Add parallel constraint/variable check to `report_numerical_issues`
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: Priority:Normal

#1403 Address many unexpected warnings in pytest
  idaes/apps/grid_integration/tests/test_bidder.py
  idaes/apps/grid_integration/tests/test_coordinator.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/apps/grid_integration/tests/test_tracker.py
  idaes/apps/grid_integration/tests/util.py
  idaes/apps/matopt/opt/pyomo_modeling.py
  idaes/core/base/tests/test_components.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/base/tests/test_flowsheet_model.py
  idaes/core/base/tests/test_property_meta.py
  idaes/core/base/tests/test_unit_model.py
  idaes/core/base/tests/test_var_like_expression.py
  idaes/core/initialization/tests/test_general_hierarchical.py
  idaes/core/initialization/tests/test_initializer_base.py
  idaes/core/solvers/tests/test_petsc.py
  idaes/core/surrogate/plotting/sm_plotter.py
  idaes/core/surrogate/plotting/tests/pysmo_krig_surrogate.json
  idaes/core/surrogate/plotting/tests/pysmo_poly_surrogate.json
  idaes/core/surrogate/plotting/tests/pysmo_rbf_surrogate.json
  idaes/core/surrogate/plotting/tests/test_alamo_plotting.py
  idaes/core/surrogate/plotting/tests/test_keras_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_krig_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_poly_plotting.py
  idaes/core/surrogate/plotting/tests/test_pysmo_rbf_plotting.py
  idaes/core/surrogate/pysmo/tests/test_kriging.py
  idaes/core/surrogate/pysmo/tests/test_polynomial_regression.py
  idaes/core/surrogate/pysmo/tests/test_radial_basis_function.py
  idaes/core/surrogate/tests/test_alamopy.py
  idaes/core/surrogate/tests/test_surrogate_block.py
  idaes/core/util/testing.py
  idaes/core/util/tests/test_config.py
  idaes/core/util/tests/test_misc.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_parameter_sweep.py
  idaes/core/util/tests/test_scaling.py
  idaes/core/util/tests/test_tables.py
  idaes/core/util/tests/test_utility_minimization.py
  idaes/models/control/tests/test_antiwindup.py
  idaes/models/properties/interrogator/tests/test_properties_interrogator.py
  idaes/models/properties/modular_properties/base/tests/test_generic_property.py
  idaes/models/properties/modular_properties/base/tests/test_generic_reaction.py
  idaes/models/properties/modular_properties/examples/reactions/tests/test_reaction_example.py
  idaes/models/properties/modular_properties/phase_equil/tests/test_henry.py
  idaes/models/properties/modular_properties/state_definitions/tests/test_FPhx.py
  idaes/models/properties/modular_properties/state_definitions/tests/test_FTPx.py
  idaes/models/properties/modular_properties/state_definitions/tests/test_FcPh.py
  idaes/models/properties/modular_properties/state_definitions/tests/test_FcTP.py
  idaes/models/properties/modular_properties/state_definitions/tests/test_FpcTP.py
  idaes/models/unit_models/solid_liquid/tests/test_thickener.py
  idaes/models/unit_models/tests/test_heat_exchanger_lc.py
  idaes/models/unit_models/tests/test_mixer.py
  idaes/models/unit_models/tests/test_mscontactor.py
  idaes/models/unit_models/tests/test_separator.py
  idaes/models_extra/power_generation/costing/tests/test_CCS_capcost.py
  idaes/models_extra/power_generation/costing/tests/test_power_plant_capcost.py
  idaes/models_extra/power_generation/properties/tests/test_flue_gas_integration.py
  idaes/models_extra/power_generation/unit_models/helm/tests/test_turbine_multistage.py
  idaes/models_extra/power_generation/unit_models/helm/tests/test_turbine_outlet.py
Labels: Priority:Normal, testing

#1402 Renaming components
  .pylint/pylintrc
  docs/reference_guides/core/var_like_expr.rst
  idaes/apps/caprese/common/config.py
  idaes/apps/caprese/controller.py
  idaes/apps/caprese/dynamic_block.py
  idaes/apps/caprese/tests/test_dynamic_block.py
  idaes/apps/caprese/util.py
  idaes/apps/matopt/opt/pyomo_modeling.py
  idaes/core/base/process_base.py
  idaes/core/base/property_base.py
  idaes/core/base/tests/test_control_volume_1d.py
  idaes/core/base/var_like_expression.py
  idaes/core/initialization/initializer_base.py
  idaes/core/plugins/variable_replace.py
  idaes/core/solvers/homotopy.py
  idaes/core/surrogate/pysmo_surrogate.py
  idaes/core/surrogate/surrogate_block.py
  idaes/core/util/expr_doc.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/model_serializer.py
  idaes/core/util/scaling.py
  idaes/core/util/tables.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_model_serializer.py
  idaes/models/properties/tests/test_harness.py
  idaes/models/unit_models/separator.py
  idaes/models_extra/power_generation/costing/power_plant_capcost.py
  setup.py
Labels: Priority:High, dependencies, pyomo, deprecation

#1406 Update the Pyomo tag to the 6.7.2 release
  setup.py
Labels: Priority:High

#1409 Infeasibility diagnostic tool
  .github/workflows/typos.toml
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: enhancement, Priority:Normal, diagnostics

#1383 Allow upwinding in 1D Heat exchanger
  idaes/logger.py
  idaes/models/unit_models/heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
  idaes/models/unit_models/tests/test_shell_and_tube_1D.py
Labels: Priority:Normal

#1413 Adding USD_2022 to units library as the most recently published value
  idaes/core/base/costing_base.py
  idaes/core/base/tests/test_costing_base.py
Labels: enhancement, Priority:Normal, WaterTAP

#1417 Option to skip parallel component checks
  idaes/core/util/model_diagnostics.py
Labels: Priority:High, diagnostics

#1420 Update pyomo requirement to 6.7.3
  setup.py
Labels: Priority:High, dependencies
