Repository IDAES/idaes-pse, pull requests merged in 2024-02, with the labels that each got.

#1332 Fixing parameter names in Perry.rst
  docs/explanations/components/property_package/general/pure/Perrys.rst
Labels: documentation, Priority:High

#1333 Updating FAQs
  CITATION.cff
  README.md
  docs/explanations/faq.rst
  docs/explanations/model_diagnostics/degeneracy_hunter.rst
  docs/explanations/model_diagnostics/svd_analysis.rst
  docs/index.rst
Labels: documentation, Priority:Normal

#1334 Extract Codecov upload steps in CI workflow to dedicated dependent job
  .github/workflows/core.yml
Labels: Priority:High

#1339 Update generic_reaction.py
  idaes/models/properties/modular_properties/base/generic_reaction.py
Labels: bug, Priority:High, property packages

#1315 Enable unnecessary-lambda Pylint check
  .pylint/pylintrc
  idaes/core/util/tables.py
Labels: Priority:Normal

#1336 Support calcuation of critical properties of mixtures in Modular Properties
  docs/explanations/components/property_package/general/eos/cubic.rst
  docs/explanations/components/property_package/general/eos/ideal.rst
  docs/explanations/components/property_package/general/phase_def.rst
  idaes/core/base/components.py
  idaes/core/base/property_meta.py
  idaes/core/base/property_set.py
  idaes/core/base/tests/test_components.py
  idaes/core/base/tests/test_property_meta.py
  idaes/models/properties/modular_properties/base/generic_property.py
  idaes/models/properties/modular_properties/base/tests/test_generic_property.py
  idaes/models/properties/modular_properties/eos/ceos.py
  idaes/models/properties/modular_properties/eos/eos_base.py
  idaes/models/properties/modular_properties/eos/tests/test_ceos_PR.py
  idaes/models/properties/modular_properties/eos/tests/test_ideal.py
Labels: enhancement, Priority:Normal, property packages, WIP, deprecation

#1284 Adding basic parameter sweep tool
  idaes/core/util/convergence/convergence_base.py
  idaes/core/util/model_diagnostics.py
  idaes/core/util/parameter_sweep.py
  idaes/core/util/tests/convergence_baseline.json
  idaes/core/util/tests/ipopt_output.txt
  idaes/core/util/tests/load_psweep.json
  idaes/core/util/tests/load_spec.json
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_parameter_sweep.py
Labels: enhancement, help wanted, Priority:Normal, core, testing, WaterTAP, WIP, PySMO, diagnostics

#1344 Update the Pyomo tag to the 6.7.1 release
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
  setup.py
Labels: Priority:High

#1305 Add diagnostics to Gibbs reactor tests
  idaes/models/unit_models/tests/test_gibbs.py
Labels: Priority:Normal, testing, unit models

#1346 Add support for Python 3.12
  .github/workflows/core.yml
  .github/workflows/integration.yml
  README.md
  docs/conf.py
  idaes/commands/__init__.py
  idaes/core/dmf/tests/test_codesearch.py
  idaes/models/properties/modular_properties/base/tests/test_generic_property.py
  setup.py
Labels: Priority:High

#1354 Pin ampl-module-scip version to 20240121
  .github/actions/setup-idaes/action.yml
Labels: Priority:High

#1357 Code clean up for Feb24 release
  .github/CODEOWNERS
  docs_archive/transformations/index.rst
  docs_archive/transformations/variable_replace.rst
Labels: Priority:Normal

#1350 Change Sphinx theme and add Intersphinx for UI and Pyomo
  docs/_templates/footer.html
  docs/_templates/page.html
  docs/conf.py
  docs/images/idaes-logo-text.png
  docs/images/ifv_annotated_screenshot.png
  docs/images/ifv_helloworld_screenshot.png
  docs/images/ifv_icon_fit.png
  docs/images/ifv_icon_zoomin.png
  docs/images/ifv_icon_zoomout.png
  docs/images/ifv_screenshot_diagram.png
  docs/images/ifv_screenshot_diagramcontrols.png
  docs/images/ifv_screenshot_streamtable.png
  docs/images/ifv_screenshot_topbar.png
  docs/images/ifv_screenshots.xcf
  docs/images/institution_logos/cmu.png
  docs/images/institution_logos/doe.jpg
  docs/images/institution_logos/gatech.png
  docs/images/institution_logos/lbnl.jpg
  docs/images/institution_logos/netl.png
  docs/images/institution_logos/snl.png
  docs/images/institution_logos/und.png
  docs/images/institution_logos/wvu.png
  docs/index.rst
  docs/static/css/custom.css
  requirements-dev.txt
Labels: documentation, Priority:Normal
