Repository IDAES/idaes-pse, pull requests merged in 2024-01, with the labels that each got.

#1316 Fix misspellings detected by typos v1.17
  idaes/core/util/utility_minimization.py
Labels: Priority:High

#1319 Add XFAIL marker to bypass #1317 known failures
  idaes/core/util/tests/test_model_diagnostics.py
Labels: Priority:High

#1318 Add preferred IDAES citation
  CITATION.cff
  docs/index.rst
Labels: Priority:High

#1320 Remove workaround for tests affected by #1317
  idaes/core/util/tests/test_model_diagnostics.py
Labels: bug, Priority:High

#1307 Add seed fixing option to PySMO's sampling methods to enhance reproducibility
  idaes/core/surrogate/pysmo/sampling.py
  idaes/core/surrogate/pysmo/tests/test_sampling.py
Labels: Priority:Normal

#1299 Adding diagnostics tools for ill conditioning
  idaes/core/util/model_diagnostics.py
  idaes/core/util/tests/test_model_diagnostics.py
Labels: enhancement, Priority:Normal, core, diagnostics
