Repository IDAES/idaes-pse, pull requests merged in 2024-04, with the labels that each got.

#1391 Fix target for 'fv' (flowsheet visualizer) reference
  docs/explanations/components/ui/index.rst
  docs/index.rst
Labels: Priority:High

#1393 Fixing spurious DoF in Gibbs reactor model
  idaes/models/unit_models/gibbs_reactor.py
  idaes/models/unit_models/tests/test_gibbs.py
Labels: bug, enhancement, Priority:Normal, unit models

#1387 Update parameter sweep tool to support indexed vars
  idaes/core/util/parameter_sweep.py
  idaes/core/util/tests/test_parameter_sweep.py
  idaes/models/unit_models/tests/test_heat_exchanger.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
Labels: enhancement, Priority:Normal, core

#1382 Crossflow hx
  docs/reference_guides/model_libraries/power_generation/unit_models/cross_flow_heat_exchanger_1D.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/heater_1D.rst
  docs/reference_guides/model_libraries/power_generation/unit_models/index.rst
  idaes/models_extra/power_generation/unit_models/__init__.py
  idaes/models_extra/power_generation/unit_models/cross_flow_heat_exchanger_1D.py
  idaes/models_extra/power_generation/unit_models/heat_exchanger_common.py
  idaes/models_extra/power_generation/unit_models/heater_1D.py
  idaes/models_extra/power_generation/unit_models/tests/test_cross_flow_heat_exchanger_1D.py
  idaes/models_extra/power_generation/unit_models/tests/test_heater_1D.py
Labels: Priority:Normal

#1400 bug fix for issue #1364: catch AttributeError in set_scaling_from_default
  idaes/core/util/scaling.py
Labels: bug, Priority:Normal
