Repository IDAES/idaes-pse, pull requests merged in 2025-02, with the labels that each got.

#1530 Fix `set_parameter_path` in Helmholtz Property Package
  idaes/models/properties/general_helmholtz/components/parameters/__init__.py
  idaes/models/properties/general_helmholtz/helmholtz_functions.py
  idaes/models/properties/general_helmholtz/helmholtz_state.py
Labels: Priority:Normal

#1564 Checks for variables with None value in NLP
  idaes/core/util/model_diagnostics.py
  idaes/core/util/model_statistics.py
  idaes/core/util/tests/test_model_diagnostics.py
  idaes/core/util/tests/test_model_statistics.py
Labels: bug, Priority:Normal

#1568 Small fixes for instructions on how to build docs locally
  docs/reference_guides/developer/howto.rst
Labels: Priority:Low

#1544 changed macosx tutorial to properly handle different mac arch possibi…
  docs/tutorials/getting_started/mac_osx.rst
Labels: documentation, Priority:Normal

#1358 Price taker model for DISPATCHES, Rehashed
  .github/workflows/typos.toml
  docs/reference_guides/apps/grid_integration/index.rst
  docs/reference_guides/apps/grid_integration/multiperiod/Price_Taker.rst
  docs/reference_guides/apps/grid_integration/multiperiod/images/hybrid_energy_system.png
  docs/reference_guides/apps/grid_integration/multiperiod/images/pricetaker.png
  docs/reference_guides/apps/grid_integration/multiperiod/index.rst
  idaes/apps/grid_integration/__init__.py
  idaes/apps/grid_integration/pricetaker/__init__.py
  idaes/apps/grid_integration/pricetaker/clustering.py
  idaes/apps/grid_integration/pricetaker/design_and_operation_models.py
  idaes/apps/grid_integration/pricetaker/price_taker_model.py
  idaes/apps/grid_integration/pricetaker/tests/__init__.py
  idaes/apps/grid_integration/pricetaker/tests/test_clustering.py
  idaes/apps/grid_integration/pricetaker/tests/test_design_and_operation_models.py
  idaes/apps/grid_integration/pricetaker/tests/test_price_taker_model.py
  idaes/apps/grid_integration/pricetaker/tests/test_unit_commitment.py
  idaes/apps/grid_integration/pricetaker/unit_commitment.py
  idaes/core/util/config.py
  idaes/core/util/tests/test_config.py
Labels: Priority:Normal, DISPATCHES, WaterTAP

#1493 Wrap 0D Fixed Bed TSA unit model in `extra_models/fixed_bed_tsa0d` for Flowsheet Processor UI
  .pylint/idaes_transform.py
  idaes/core/base/flowsheet_model.py
  idaes/models_extra/temperature_swing_adsorption/fixed_bed_tsa0d_ui.py
  idaes/models_extra/temperature_swing_adsorption/tests/test_fixed_bed_tsa0d_ui.py
  requirements-dev.txt
  setup.py
Labels: Priority:Normal, dependencies

#1550 updated importlib.resources to stop using deprecated path function
  idaes/apps/grid_integration/examples/utils.py
  idaes/apps/grid_integration/tests/test_integration.py
  idaes/tests/prescient/test_prescient.py
Labels: Priority:Normal

#1563 Fix bugs in SmoothVLE2 initialization
  idaes/models/properties/modular_properties/phase_equil/smooth_VLE_2.py
  idaes/models/properties/modular_properties/phase_equil/tests/test_smooth_VLE_2.py
  idaes/models/unit_models/tests/test_heat_exchanger_1D.py
Labels: Priority:Normal

#1559 Add mapping to use ubuntu2204 build of idaes-ext on Ubuntu 24.04
  .github/actions/setup-idaes/action.yml
  .github/workflows/core.yml
  .github/workflows/integration.yml
  idaes/config.py
Labels: Priority:High

#1572 Temporarily exclude sphinx 8.2.0 to fix doctests
  requirements-dev.txt
Labels: Priority:High

#1571 Update Pyomo requirement to the 6.9.0 release
  idaes/core/util/tests/test_model_diagnostics.py
  setup.py
Labels: Priority:High, dependencies, pyomo
